section1_score: 'Food governance & strategy' , section2_score: 'Community food growing', section3_score: 'Community food action', section14_score: 'Stemming the flood of unhealthy food', section15_score: 'Sustainable food economy', section16_score: 'Catering & procurement', section17_score: 'Food for the planet', section99_score: 'Ethnic and cultural diversity in the food system'

In [ ]:

import xml.etree.ElementTree as ET
import pandas as pd

# 1. Load your XML (make sure 'capitalgrowth-london.xml' is in your notebook dir)
tree = ET.parse('../myenv/capstone data/good-food-local-ap-2025_table_xml.php.xml')
root = tree.getroot()

# 2. Build a list of dicts, one per <marker>
records = []
for m in root.findall('marker'):
    # Grab every attribute on this element
    attrs = m.attrib.copy()
    records.append(attrs)

# 3. Turn into a DataFrame
df = pd.DataFrame(records)

# 4. Quick sanity‐check
print(df.shape, "markers loaded")
df

(33, 25) markers loaded

,CTYUA21CD,CTYUA21NM,overall_score,fpoverall_score,section1_score,section2_score,section3_score,section4_score,section5_score,section6_score,...,section12_score,section13_score,section14_score,section15_score,section16_score,section17_score,section18_score,section19_score,section20_score,section99_score
0,E09000025,Newham,54,30,3,3,3,3,3,3,...,3,3,3,3,3,3,,,3,3
1,E09000019,Islington,53,31,3,3,3,3,3,2,...,3,3,2,3,2,3,,,3,3
2,E09000022,Lambeth,53,30,3,3,3,3,3,3,...,3,3,2,3,3,3,,,3,3
3,E09000011,Greenwich,51,29,2,3,3,3,3,3,...,2,3,3,3,2,3,,,3,3
4,E09000013,Hammersmith and Fulham,51,30,3,3,3,3,3,2,...,2,3,2,3,1,3,,,3,3
5,E09000028,Southwark,51,30,3,3,3,3,3,3,...,3,3,3,3,1,2,,,3,3
6,E09000030,Tower Hamlets,48,27,2,3,3,3,3,3,...,3,3,3,2,2,3,,,1,3
7,E09000007,Camden,47,28,3,2,3,3,3,3,...,3,3,2,2,2,2,,,3,3
8,E09000005,Brent,45,26,2,3,3,3,3,2,...,2,2,2,3,1,2,,,1,3
9,E09000012,Hackney,45,26,1,2,3,3,3,3,...,3,3,2,2,3,3,,,2,3
10,E09000002,Barking and Dagenham,44,23,3,3,3,3,3,2,...,2,3,2,3,3,2,,,1,2
11,E09000033,Westminster,44,28,1,2,3,3,2,3,...,3,3,2,2,1,2,,,2,3
12,E09000009,Ealing,43,26,3,3,3,3,0,3,...,3,3,1,1,1,3,,,2,2
13,E09000021,Kingston upon Thames,43,26,1,3,3,3,3,2,...,2,3,2,2,1,2,,,3,3
14,E09000023,Lewisham,43,23,3,3,3,3,3,2,...,2,3,2,3,1,2,,,1,3
15,E09000024,Merton,42,27,2,3,2,3,3,3,...,3,3,2,2,1,1,,,1,2
16,E09000020,Kensington and Chelsea,40,24,1,2,3,3,0,3,...,2,2,2,2,1,3,,,3,2
17,E09000031,Waltham Forest,40,22,2,3,3,3,1,2,...,2,2,2,2,1,2,,,2,3
18,E09000003,Barnet,38,24,3,2,3,3,2,2,...,3,3,1,1,1,1,,,3,2
19,E09000014,Haringey,37,21,1,2,2,2,1,3,...,2,3,3,2,1,2,,,1,3
20,E09000018,Hounslow,35,20,1,2,2,3,1,2,...,1,3,2,1,3,2,,,1,2
21,E09000010,Enfield,34,21,1,3,1,3,1,3,...,2,2,2,1,1,2,,,2,2
22,E09000032,Wandsworth,34,18,1,3,2,0,1,2,...,3,2,2,1,1,3,,,1,3
23,E09000027,Richmond upon Thames,33,19,1,2,2,3,1,2,...,2,3,2,1,1,3,,,1,2
24,E09000026,Redbridge,32,20,1,1,3,3,1,2,...,2,3,1,1,1,1,,,1,3
25,E09000016,Havering,29,19,0,2,2,2,1,3,...,2,2,2,1,1,1,,,2,1
26,E09000015,Harrow,27,16,0,3,2,0,0,2,...,2,3,1,1,0,2,,,2,2
27,E09000004,Bexley,26,16,1,2,1,3,0,1,...,1,3,1,1,1,2,,,1,1
28,E09000017,Hillingdon,26,17,1,1,2,0,1,2,...,2,1,1,1,1,1,,,1,1
29,E09000029,Sutton,24,16,0,1,2,3,0,2,...,0,2,1,1,1,1,,,1,1
30,E09000008,Croydon,19,15,1,2,0,2,0,,...,2,3,0,,0,0,,,1,1
31,E09000001,City of London,3,2,,,,,,,...,,,1,,,,,,,
32,E09000006,Bromley,2,2,,,,,,,...,,,0,,,,,,,

In [3]:
df = df.rename(columns={
        "section1_score": 'Food governance & strategy' , "section2_score": 'Community food growing', "section3_score": 'Community food action', "section14_score": 'Stemming the flood of unhealthy food', "section15_score": 'Sustainable food economy', "section16_score": 'Catering & procurement', "section17_score": 'Food for the planet', "section99_score": 'Ethnic and cultural diversity in the food system'
    })
df

,CTYUA21CD,CTYUA21NM,overall_score,fpoverall_score,Food governance & strategy,Community food growing,Community food action,section4_score,section5_score,section6_score,...,section12_score,section13_score,Stemming the flood of unhealthy food,Sustainable food economy,Catering & procurement,Food for the planet,section18_score,section19_score,section20_score,Ethnic and cultural diversity in the food system
0,E09000025,Newham,54,30,3,3,3,3,3,3,...,3,3,3,3,3,3,,,3,3
1,E09000019,Islington,53,31,3,3,3,3,3,2,...,3,3,2,3,2,3,,,3,3
2,E09000022,Lambeth,53,30,3,3,3,3,3,3,...,3,3,2,3,3,3,,,3,3
3,E09000011,Greenwich,51,29,2,3,3,3,3,3,...,2,3,3,3,2,3,,,3,3
4,E09000013,Hammersmith and Fulham,51,30,3,3,3,3,3,2,...,2,3,2,3,1,3,,,3,3
5,E09000028,Southwark,51,30,3,3,3,3,3,3,...,3,3,3,3,1,2,,,3,3
6,E09000030,Tower Hamlets,48,27,2,3,3,3,3,3,...,3,3,3,2,2,3,,,1,3
7,E09000007,Camden,47,28,3,2,3,3,3,3,...,3,3,2,2,2,2,,,3,3
8,E09000005,Brent,45,26,2,3,3,3,3,2,...,2,2,2,3,1,2,,,1,3
9,E09000012,Hackney,45,26,1,2,3,3,3,3,...,3,3,2,2,3,3,,,2,3
10,E09000002,Barking and Dagenham,44,23,3,3,3,3,3,2,...,2,3,2,3,3,2,,,1,2
11,E09000033,Westminster,44,28,1,2,3,3,2,3,...,3,3,2,2,1,2,,,2,3
12,E09000009,Ealing,43,26,3,3,3,3,0,3,...,3,3,1,1,1,3,,,2,2
13,E09000021,Kingston upon Thames,43,26,1,3,3,3,3,2,...,2,3,2,2,1,2,,,3,3
14,E09000023,Lewisham,43,23,3,3,3,3,3,2,...,2,3,2,3,1,2,,,1,3
15,E09000024,Merton,42,27,2,3,2,3,3,3,...,3,3,2,2,1,1,,,1,2
16,E09000020,Kensington and Chelsea,40,24,1,2,3,3,0,3,...,2,2,2,2,1,3,,,3,2
17,E09000031,Waltham Forest,40,22,2,3,3,3,1,2,...,2,2,2,2,1,2,,,2,3
18,E09000003,Barnet,38,24,3,2,3,3,2,2,...,3,3,1,1,1,1,,,3,2
19,E09000014,Haringey,37,21,1,2,2,2,1,3,...,2,3,3,2,1,2,,,1,3
20,E09000018,Hounslow,35,20,1,2,2,3,1,2,...,1,3,2,1,3,2,,,1,2
21,E09000010,Enfield,34,21,1,3,1,3,1,3,...,2,2,2,1,1,2,,,2,2
22,E09000032,Wandsworth,34,18,1,3,2,0,1,2,...,3,2,2,1,1,3,,,1,3
23,E09000027,Richmond upon Thames,33,19,1,2,2,3,1,2,...,2,3,2,1,1,3,,,1,2
24,E09000026,Redbridge,32,20,1,1,3,3,1,2,...,2,3,1,1,1,1,,,1,3
25,E09000016,Havering,29,19,0,2,2,2,1,3,...,2,2,2,1,1,1,,,2,1
26,E09000015,Harrow,27,16,0,3,2,0,0,2,...,2,3,1,1,0,2,,,2,2
27,E09000004,Bexley,26,16,1,2,1,3,0,1,...,1,3,1,1,1,2,,,1,1
28,E09000017,Hillingdon,26,17,1,1,2,0,1,2,...,2,1,1,1,1,1,,,1,1
29,E09000029,Sutton,24,16,0,1,2,3,0,2,...,0,2,1,1,1,1,,,1,1
30,E09000008,Croydon,19,15,1,2,0,2,0,,...,2,3,0,,0,0,,,1,1
31,E09000001,City of London,3,2,,,,,,,...,,,1,,,,,,,
32,E09000006,Bromley,2,2,,,,,,,...,,,0,,,,,,,

In [4]:
df.columns

Index(['CTYUA21CD', 'CTYUA21NM', 'overall_score', 'fpoverall_score',
       'Food governance & strategy', 'Community food growing',
       'Community food action', 'section4_score', 'section5_score',
       'section6_score', 'section7_score', 'section8_score', 'section9_score',
       'section10_score', 'section11_score', 'section12_score',
       'section13_score', 'Stemming the flood of unhealthy food',
       'Sustainable food economy', 'Catering & procurement',
       'Food for the planet', 'section18_score', 'section19_score',
       'section20_score', 'Ethnic and cultural diversity in the food system'],
      dtype='object')

In [5]:
df = df.drop(columns= ['CTYUA21CD', 'section4_score', 'section5_score',
       'section6_score', 'section7_score', 'section8_score', 'section9_score',
       'section10_score', 'section11_score', 'section12_score',  'section13_score', 'section18_score', 'section19_score',
       'section20_score'])
df

,CTYUA21NM,overall_score,fpoverall_score,Food governance & strategy,Community food growing,Community food action,Stemming the flood of unhealthy food,Sustainable food economy,Catering & procurement,Food for the planet,Ethnic and cultural diversity in the food system
0,Newham,54,30,3,3,3,3,3,3,3,3
1,Islington,53,31,3,3,3,2,3,2,3,3
2,Lambeth,53,30,3,3,3,2,3,3,3,3
3,Greenwich,51,29,2,3,3,3,3,2,3,3
4,Hammersmith and Fulham,51,30,3,3,3,2,3,1,3,3
5,Southwark,51,30,3,3,3,3,3,1,2,3
6,Tower Hamlets,48,27,2,3,3,3,2,2,3,3
7,Camden,47,28,3,2,3,2,2,2,2,3
8,Brent,45,26,2,3,3,2,3,1,2,3
9,Hackney,45,26,1,2,3,2,2,3,3,3
10,Barking and Dagenham,44,23,3,3,3,2,3,3,2,2
11,Westminster,44,28,1,2,3,2,2,1,2,3
12,Ealing,43,26,3,3,3,1,1,1,3,2
13,Kingston upon Thames,43,26,1,3,3,2,2,1,2,3
14,Lewisham,43,23,3,3,3,2,3,1,2,3
15,Merton,42,27,2,3,2,2,2,1,1,2
16,Kensington and Chelsea,40,24,1,2,3,2,2,1,3,2
17,Waltham Forest,40,22,2,3,3,2,2,1,2,3
18,Barnet,38,24,3,2,3,1,1,1,1,2
19,Haringey,37,21,1,2,2,3,2,1,2,3
20,Hounslow,35,20,1,2,2,2,1,3,2,2
21,Enfield,34,21,1,3,1,2,1,1,2,2
22,Wandsworth,34,18,1,3,2,2,1,1,3,3
23,Richmond upon Thames,33,19,1,2,2,2,1,1,3,2
24,Redbridge,32,20,1,1,3,1,1,1,1,3
25,Havering,29,19,0,2,2,2,1,1,1,1
26,Harrow,27,16,0,3,2,1,1,0,2,2
27,Bexley,26,16,1,2,1,1,1,1,2,1
28,Hillingdon,26,17,1,1,2,1,1,1,1,1
29,Sutton,24,16,0,1,2,1,1,1,1,1
30,Croydon,19,15,1,2,0,0,,0,0,1
31,City of London,3,2,,,,1,,,,
32,Bromley,2,2,,,,0,,,,

good for big picture but not detail