In [32]:
import pandas as pd 

rev = pd.read_csv('../myenv/capstone data/Revenue_Outturn_time_series_data_v2.3.csv')
rev

,year_ending,ONS_code,LA_LGF_code,LA_name,status,LA_class,LA_subclass,RG_grantindsg_tot_grant,RG_grantinppg_tot_grant,RG_grantinusm_tot_grant,...,TSR_caploss_ext,TSR_caploss_int,TSR_capreval_ext,TSR_capreval_int,TSR_capgrant_ext,TSR_capgrant_int,TSR_caprecs_ext,TSR_caprecs_int,TSR_capsum_ext,TSR_capsum_int
0,202403,E06000001,E0701,Hartlepool UA,submitted,Unitary Authority,Unitary Authority,42564.0,3363.0,242.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,202403,E06000002,E0702,Middlesbrough UA,submitted,Unitary Authority,Unitary Authority,59739.0,3966.0,383.0,...,0.0,0.0,1213.0,0.0,0.0,0.0,0.0,0.0,1953.0,0.0
2,202403,E06000003,E0703,Redcar & Cleveland UA,submitted,Unitary Authority,Unitary Authority,41494.0,1928.0,247.0,...,618.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,683.0,0.0
3,202403,E06000004,E0704,Stockton-on-Tees UA,submitted,Unitary Authority,Unitary Authority,81821.0,4515.0,530.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,202403,E06000005,E1301,Darlington UA,submitted,Unitary Authority,Unitary Authority,29728.0,1320.0,94.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,201803,E08,MD,Metropolitan Districts,total,Met District,Met District,6358721.0,435608.0,108186.0,...,-963.0,532.0,-10467.0,1733.0,-448.0,-15.0,28.0,438.0,-6570.0,17053.0
3077,201803,E06,UA,Unitary Authorities,total,Unitary Authority,Unitary Authority,5436305.0,287940.0,94188.0,...,1136.0,36.0,-13046.0,1656.0,-1565.0,371.0,1379.0,2.0,841.0,18929.0
3078,201803,E10,SC,Shire Counties,total,Shire County,Shire County,9332326.0,402711.0,173767.0,...,0.0,0.0,18.0,-19.0,0.0,0.0,0.0,0.0,28.0,2449.0
3079,201803,E07,SD,Shire Districts,total,Shire District,Shire District,0.0,0.0,0.0,...,8224.0,-548.0,-18382.0,-1.0,2663.0,-47.0,7203.0,0.0,14574.0,5964.0
3080,201803,EOTH,O,Other Authorities,total,Other,Other,0.0,0.0,0.0,...,670.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9726.0,0.0

In [33]:
rev['year_ending'].dtypes

dtype('int64')

In [34]:
rev["year_ending"] = rev["year_ending"].astype(str).str[:4]

In [35]:

dict = pd.read_excel("../myenv/capstone data/Revenue_Outturn_metadata.xlsx", sheet_name="Data_dictionary", header=3)
dict = dict[['Data item name', 'Description', 'Form name']]
dict

,Data item name,Description,Form name
0,year_ending,The date in YYYYMM format which represents the...,all
1,ONS_code,The ONS local authority code.,all
2,LA_LGF_code,"A Local Government Finance code, which MHCLG u...",all
3,LA_name,The name of the local authority.,all
4,status,The submission status. Takes one of three valu...,all
...,...,...,...
2319,TSR_capgrant_int,Internal Trading Accounts - Capital Items - Cr...,TSR
2320,TSR_caprecs_ext,External Trading Accounts - Capital Items - Re...,TSR
2321,TSR_caprecs_int,Internal Trading Accounts - Capital Items - Re...,TSR
2322,TSR_capsum_ext,External Trading Accounts - Capital Items - To...,TSR
2323,TSR_capsum_int,Internal Trading Accounts - Capital Items - To...,TSR

In [36]:

def extract_theme(var):
    parts = var.split("_")
    if len(parts) >= 3:
        return parts[1]   # middle part is theme
    elif len(parts) == 2:
        return parts[1]   # if only 2 parts, treat second as theme
    else:
        return None

dict['Theme'] = dict['Data item name'].apply(extract_theme)
dict['Theme'].value_counts()

Theme
housgfcfhml    168
tradaccint      65
tradaccext      58
cencnt          35
frs             29
              ...
hbnreb           1
hbhreb           1
hbsubl           1
hbhrashare       1
ending           1
Name: count, Length: 453, dtype: int64

In [37]:
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_rows', 20)
theme_counts = dict["Theme"].value_counts(dropna=False)
dict["Theme_count"] = dict["Theme"].map(theme_counts)
not_done = dict[dict["Theme_count"] < 2]
not_done

,Data item name,Description,Form name,Theme,Theme_count
0,year_ending,The date in YYYYMM format which represents the...,all,ending,1
1,ONS_code,The ONS local authority code.,all,code,1
2,LA_LGF_code,"A Local Government Finance code, which MHCLG u...",all,LGF,1
3,LA_name,The name of the local authority.,all,name,1
4,status,The submission status. Takes one of three valu...,all,None,1
...,...,...,...,...,...
2033,RS_lctstot_net_exp,lcts - Total amount of council tax revenue for...,RS,lctstot,1
2034,RS_lctsparish_net_exp,lcts - The total amount paid to local parishes...,RS,lctsparish,1
2051,RS_appresothearA_net_exp,Appropriations to/from other earmarked financi...,RS,appresothearA,1
2052,RS_appresothearB_net_exp,Appropriations to/from other earmarked financi...,RS,appresothearB,1
2053,RS_appresothearC_net_exp,Appropriations to/from other earmarked financi...,RS,appresothearC,1

In [38]:
dict

,Data item name,Description,Form name,Theme,Theme_count
0,year_ending,The date in YYYYMM format which represents the...,all,ending,1
1,ONS_code,The ONS local authority code.,all,code,1
2,LA_LGF_code,"A Local Government Finance code, which MHCLG u...",all,LGF,1
3,LA_name,The name of the local authority.,all,name,1
4,status,The submission status. Takes one of three valu...,all,None,1
...,...,...,...,...,...
2319,TSR_capgrant_int,Internal Trading Accounts - Capital Items - Cr...,TSR,capgrant,3
2320,TSR_caprecs_ext,External Trading Accounts - Capital Items - Re...,TSR,caprecs,3
2321,TSR_caprecs_int,Internal Trading Accounts - Capital Items - Re...,TSR,caprecs,3
2322,TSR_capsum_ext,External Trading Accounts - Capital Items - To...,TSR,capsum,2
2323,TSR_capsum_int,Internal Trading Accounts - Capital Items - To...,TSR,capsum,2

In [39]:
import re
RULES = [
    # --- Service areas ---
    (r"^edu",                   "Education"),
    (r"^csc",                   "Children’s Social Care"),
    (r"^asc",                   "Adult Social Care"),
    (r"^ph",                    "Public Health"),
    (r"^hous",                  "Housing"),
    (r"^hra",                   "Housing Revenue Account"),
    (r"^cul",                   "Culture"),
    (r"^env",                   "Environment"),
    (r"^plan",                  "Planning & Development"),
    (r"^culenvplan",           "Culture / Environment / Planning"),  # if mixed prefix
    (r"^pol",                   "Police"),
    (r"^frs",                   "Fire & Rescue"),
    (r"^cen",                   "Central Services"),
    (r"^trans",                 "Transport"),
    (r"^grant",                 "Grants"),
    (r"^totsx",                 "Total Service Expenditure"),

    # --- Financing & reserves ---
    (r"^levy",                  "Levies"),
    (r"^res",                   "Reserves"),
    (r"^app",                   "Appropriations"),
    (r"^adj",                   "Adjustments"),
    (r"^cap",                   "Capital"),
    (r"^prov",                  "Provisions"),
    (r"^pyadj",                 "Prior Year Adjustments"),

    # --- Income & trading ---
    (r"^inc",                   "Income"),
    (r"^int",                   "Interest"),
    (r"^invprp",                "Investment Properties"),
    (r"^trad",                  "Trading"),
    (r"^hb",                    "Housing Benefits"),
    (r"^brsupp",                "Business Rates Support"),
    (r"^netrevexp",             "Net Revenue Expenditure"),
    (r"^netcurrtot",           "Net Current Expenditure"),

    # --- Special ---
    (r"^cv19",                  "COVID-19"),
    (r"^dsb",                   "Disbursements"),
    (r"^equal",                 "Equal Pay"),
    (r"^sub",                   "Subsidies"),
    (r"^sfc",                   "Schools Funding"),
    (r"^cera",                  "Collection Fund Adjustments"),
]

def to_theme_group(theme: str) -> str:
    if not isinstance(theme, str):
        return "Other / Unmapped"
    t = theme.lower()
    for pat, label in RULES:
        if re.match(pat, t, flags=re.IGNORECASE):
            return label
    return "Other / Unmapped"

dict["Theme_group"] = dict["Theme"].apply(to_theme_group)

In [40]:
dict

,Data item name,Description,Form name,Theme,Theme_count,Theme_group
0,year_ending,The date in YYYYMM format which represents the...,all,ending,1,Other / Unmapped
1,ONS_code,The ONS local authority code.,all,code,1,Other / Unmapped
2,LA_LGF_code,"A Local Government Finance code, which MHCLG u...",all,LGF,1,Other / Unmapped
3,LA_name,The name of the local authority.,all,name,1,Other / Unmapped
4,status,The submission status. Takes one of three valu...,all,None,1,Other / Unmapped
...,...,...,...,...,...,...
2319,TSR_capgrant_int,Internal Trading Accounts - Capital Items - Cr...,TSR,capgrant,3,Capital
2320,TSR_caprecs_ext,External Trading Accounts - Capital Items - Re...,TSR,caprecs,3,Capital
2321,TSR_caprecs_int,Internal Trading Accounts - Capital Items - Re...,TSR,caprecs,3,Capital
2322,TSR_capsum_ext,External Trading Accounts - Capital Items - To...,TSR,capsum,2,Capital
2323,TSR_capsum_int,Internal Trading Accounts - Capital Items - To...,TSR,capsum,2,Capital

In [41]:
dict['Theme_group'].value_counts()

Theme_group
Central Services           323
Housing                    261
Adult Social Care          241
Public Health              216
Environment                212
                          ...
Business Rates Support       1
Net Revenue Expenditure      1
Schools Funding              1
COVID-19                     1
Prior Year Adjustments       1
Name: count, Length: 37, dtype: int64

In [42]:
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_rows', 20)

In [43]:

df = dict.copy()

df["parts"] = df["Data item name"].astype(str).str.split("_")

# last chunk
df["last1"] = df["parts"].str[-1]

# second to last chunk
df["last2"] = df["parts"].str[-2]

df["last1"].value_counts()

last1
exp       988
inc       583
sfc       264
empl      262
grant      66
         ...
end         1
class       1
status      1
name        1
ending      1
Name: count, Length: 21, dtype: int64

last1["exp": "Expenditure", "inc": "Income", "sfc": "Sales, Fees and Charges", "empl": "Employees", "grant": "Grant", "SurDef": "Surplus/Deficit", "Cap":??, "ext": "External", "int": "Internal"]
last2["tot": "Total", "oth": "Other", "run": , "cur": , "net": "Net", "gross": "Gross"]

In [44]:

last1_map = {
    "exp":   "Expenditure",
    "inc":   "Income",
    "sfc":   "Sales, Fees & Charges",
    "empl":  "Employees",
    "grant": "Grant",
    "surdef":"Surplus/Deficit",
    "cap":   "Capital",
    "ext":   "External",
    "int":   "Internal",
}

last2_map = {
    "tot":   "Total",
    "net":   "Net",
    "gross": "Gross",
    "run":   "Running expenses"
}


# Apply mapping to create two new columns
df["measure1"] = df["last1"].map(last1_map).fillna("Other/Unmapped")
df["measure2"] = df["last2"].map(last2_map).fillna("Other/Unmapped")

In [45]:
df

,Data item name,Description,Form name,Theme,Theme_count,Theme_group,parts,last1,last2,measure1,measure2
0,year_ending,The date in YYYYMM format which represents the...,all,ending,1,Other / Unmapped,"[year, ending]",ending,year,Other/Unmapped,Other/Unmapped
1,ONS_code,The ONS local authority code.,all,code,1,Other / Unmapped,"[ONS, code]",code,ONS,Other/Unmapped,Other/Unmapped
2,LA_LGF_code,"A Local Government Finance code, which MHCLG u...",all,LGF,1,Other / Unmapped,"[LA, LGF, code]",code,LGF,Other/Unmapped,Other/Unmapped
3,LA_name,The name of the local authority.,all,name,1,Other / Unmapped,"[LA, name]",name,LA,Other/Unmapped,Other/Unmapped
4,status,The submission status. Takes one of three valu...,all,None,1,Other / Unmapped,[status],status,NaN,Other/Unmapped,Other/Unmapped
...,...,...,...,...,...,...,...,...,...,...,...
2319,TSR_capgrant_int,Internal Trading Accounts - Capital Items - Cr...,TSR,capgrant,3,Capital,"[TSR, capgrant, int]",int,capgrant,Internal,Other/Unmapped
2320,TSR_caprecs_ext,External Trading Accounts - Capital Items - Re...,TSR,caprecs,3,Capital,"[TSR, caprecs, ext]",ext,caprecs,External,Other/Unmapped
2321,TSR_caprecs_int,Internal Trading Accounts - Capital Items - Re...,TSR,caprecs,3,Capital,"[TSR, caprecs, int]",int,caprecs,Internal,Other/Unmapped
2322,TSR_capsum_ext,External Trading Accounts - Capital Items - To...,TSR,capsum,2,Capital,"[TSR, capsum, ext]",ext,capsum,External,Other/Unmapped
2323,TSR_capsum_int,Internal Trading Accounts - Capital Items - To...,TSR,capsum,2,Capital,"[TSR, capsum, int]",int,capsum,Internal,Other/Unmapped

In [46]:
df.loc[df["Data item name"] == "year_ending", "Description"] = "Year"

In [47]:
df = df.drop(columns=["parts", "last1", "last2"])
df

,Data item name,Description,Form name,Theme,Theme_count,Theme_group,measure1,measure2
0,year_ending,Year,all,ending,1,Other / Unmapped,Other/Unmapped,Other/Unmapped
1,ONS_code,The ONS local authority code.,all,code,1,Other / Unmapped,Other/Unmapped,Other/Unmapped
2,LA_LGF_code,"A Local Government Finance code, which MHCLG u...",all,LGF,1,Other / Unmapped,Other/Unmapped,Other/Unmapped
3,LA_name,The name of the local authority.,all,name,1,Other / Unmapped,Other/Unmapped,Other/Unmapped
4,status,The submission status. Takes one of three valu...,all,None,1,Other / Unmapped,Other/Unmapped,Other/Unmapped
...,...,...,...,...,...,...,...,...
2319,TSR_capgrant_int,Internal Trading Accounts - Capital Items - Cr...,TSR,capgrant,3,Capital,Internal,Other/Unmapped
2320,TSR_caprecs_ext,External Trading Accounts - Capital Items - Re...,TSR,caprecs,3,Capital,External,Other/Unmapped
2321,TSR_caprecs_int,Internal Trading Accounts - Capital Items - Re...,TSR,caprecs,3,Capital,Internal,Other/Unmapped
2322,TSR_capsum_ext,External Trading Accounts - Capital Items - To...,TSR,capsum,2,Capital,External,Other/Unmapped
2323,TSR_capsum_int,Internal Trading Accounts - Capital Items - To...,TSR,capsum,2,Capital,Internal,Other/Unmapped

In [48]:
dict.to_csv("../myenv/capstone data/Revenue_metadata_dict.csv", index=False)

In [49]:
def norm_code(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.strip()
    # match dd's hyphenated codes to underscore-coded_df columns
    return re.sub(r"[^0-9a-zA-Z_]+", "", s.replace("-", "_")).lower()

# Build normalized lookup maps from df
df_norm = df.copy()
df_norm["code_norm"] = df_norm["Data item name"].astype(str).map(norm_code)

sub_theme_map = df_norm.set_index("code_norm")["Theme"].to_dict()
theme_map     = df_norm.set_index("code_norm")["Theme_group"].to_dict()

# Prepare column arrays
orig_cols  = list(rev.columns)
norm_cols  = [norm_code(c) for c in orig_cols]
themes     = [theme_map.get(nc, "") for nc in norm_cols]      # top-level
subthemes  = [sub_theme_map.get(nc, "") for nc in norm_cols]  # second-level

# Apply MultiIndex columns
multi = rev.copy()
multi.columns = pd.MultiIndex.from_arrays(
    [themes, subthemes, orig_cols],
    names=["theme", "sub_theme", "Variable"]
)

# Quick coverage check
matched = sum(bool(t or st) for t, st in zip(themes, subthemes))
print(f"Matched metadata for {matched} / {len(orig_cols)} columns.")

Matched metadata for 2323 / 2323 columns.

In [50]:
multi

theme     Other / Unmapped                                                 \
sub_theme           ending       code         LGF                    name
Variable       year_ending   ONS_code LA_LGF_code                 LA_name
0                     2024  E06000001       E0701           Hartlepool UA
1                     2024  E06000002       E0702        Middlesbrough UA
2                     2024  E06000003       E0703   Redcar & Cleveland UA
3                     2024  E06000004       E0704     Stockton-on-Tees UA
4                     2024  E06000005       E1301           Darlington UA
...                    ...        ...         ...                     ...
3076                  2018        E08          MD  Metropolitan Districts
3077                  2018        E06          UA     Unitary Authorities
3078                  2018        E10          SC          Shire Counties
3079                  2018        E07          SD         Shire Districts
3080                  2018       EOTH           O       Other Authorities

theme                                            Subsidies  \
sub_theme        NaN              class           subclass
Variable      status           LA_class        LA_subclass
0          submitted  Unitary Authority  Unitary Authority
1          submitted  Unitary Authority  Unitary Authority
2          submitted  Unitary Authority  Unitary Authority
3          submitted  Unitary Authority  Unitary Authority
4          submitted  Unitary Authority  Unitary Authority
...              ...                ...                ...
3076           total       Met District       Met District
3077           total  Unitary Authority  Unitary Authority
3078           total       Shire County       Shire County
3079           total     Shire District     Shire District
3080           total              Other              Other

theme                      Grants                          \
sub_theme              grantindsg              grantinppg
Variable  RG_grantindsg_tot_grant RG_grantinppg_tot_grant
0                         42564.0                  3363.0
1                         59739.0                  3966.0
2                         41494.0                  1928.0
3                         81821.0                  4515.0
4                         29728.0                  1320.0
...                           ...                     ...
3076                    6358721.0                435608.0
3077                    5436305.0                287940.0
3078                    9332326.0                402711.0
3079                          0.0                     0.0
3080                          0.0                     0.0

theme                              ...         Capital                  \
sub_theme              grantinusm  ...         caploss
Variable  RG_grantinusm_tot_grant  ... TSR_caploss_ext TSR_caploss_int
0                           242.0  ...             0.0             0.0
1                           383.0  ...             0.0             0.0
2                           247.0  ...           618.0             0.0
3                           530.0  ...             0.0             0.0
4                            94.0  ...             0.0             0.0
...                           ...  ...             ...             ...
3076                     108186.0  ...          -963.0           532.0
3077                      94188.0  ...          1136.0            36.0
3078                     173767.0  ...             0.0             0.0
3079                          0.0  ...          8224.0          -548.0
3080                          0.0  ...           670.0             0.0

theme                                                                          \
sub_theme         capreval                          capgrant
Variable  TSR_capreval_ext TSR_capreval_int TSR_capgrant_ext TSR_capgrant_int
0                      0.0              0.0              0.0              0.0
1                   1213.0              0.0              0.0              0.0
2                      0.0              0.0              0.0              0.0
3                      0.0              0.0              0.0              0.0
4                      0.0              0.0              0.0              0.0
...                    ...              ...              ...              ...
3076              -10467.0           1733.0           -448.0            -15.0
3077              -13046.0           1656.0          -1565.0            371.0
3078                  18.0            -19.0              0.0              0.0
3079              -18382.0             -1.0           2663.0            -47.0
3080                   0.0              0.0              0.0              0.0

theme
sub_theme         caprecs                         capsum
Variable  TSR_caprecs_ext TSR_caprecs_int TSR_capsum_ext TSR_capsum_int
0                     0.0             0.0            0.0            0.0
1                     0.0             0.0         1953.0            0.0
2                     0.0             0.0          683.0            0.0
3                     0.0             0.0            0.0            0.0
4                     0.0             0.0            0.0            0.0
...                   ...             ...            ...            ...
3076                 28.0           438.0        -6570.0        17053.0
3077               1379.0             2.0          841.0        18929.0
3078                  0.0             0.0           28.0         2449.0
3079               7203.0             0.0        14574.0         5964.0
3080                  0.0             0.0         9726.0            0.0

[3081 rows x 2323 columns]

In [51]:
def _norm_code(s: str) -> str:
    s = str(s).strip().replace("-", "_")
    s = re.sub(r"[^0-9A-Za-z_]", "", s)
    return s.lower()

# 1) build code -> description mapping from dd
md = df.loc[:, ["Data item name", "Description"]].dropna(subset=["Data item name"]).copy()
md["code_norm"] = md["Data item name"].map(_norm_code)
code2desc = md.set_index("code_norm")["Description"].to_dict()

# 2) find which level in df_multi is the 'code' level
col_names = list(multi.columns.names)
try:
    code_level = col_names.index("code")
except ValueError:
    # if not explicitly named, assume last level is the code
    code_level = len(col_names) - 1

# 3) build new tuples with description inserted just before code
new_tuples = []
matched = 0
for tpl in multi.columns.to_flat_index():
    tpl = tpl if isinstance(tpl, tuple) else (tpl,)
    code = tpl[code_level]
    desc = code2desc.get(_norm_code(code), "")
    if desc:
        matched += 1
    new_tpl = tuple(list(tpl[:code_level]) + [desc] + list(tpl[code_level:]))
    new_tuples.append(new_tpl)

# 4) assign the new MultiIndex (… , 'description', 'code')
new_names = list(col_names)
new_names.insert(code_level, "description")

multi_desc = multi.copy()
multi_desc.columns = pd.MultiIndex.from_tuples(new_tuples, names=new_names)

print(f"Added descriptions for {matched} / {len(multi.columns)} columns.")
print("Column levels now:", multi_desc.columns.names)

Added descriptions for 2323 / 2323 columns.
Column levels now: ['theme', 'sub_theme', 'description', 'Variable']

In [52]:
multi_desc

theme       Other / Unmapped                                \
sub_theme             ending                          code
description             Year The ONS local authority code.
Variable         year_ending                      ONS_code
0                       2024                     E06000001
1                       2024                     E06000002
2                       2024                     E06000003
3                       2024                     E06000004
4                       2024                     E06000005
...                      ...                           ...
3076                    2018                           E08
3077                    2018                           E06
3078                    2018                           E10
3079                    2018                           E07
3080                    2018                          EOTH

theme                                                                                                                                                                                        \
sub_theme                                                                                                                                                                               LGF
description A Local Government Finance code, which MHCLG uses internally to represent local authorities. These are unique to each local authority, similar to the ONS local authority code.
Variable                                                                                                                                                                        LA_LGF_code
0                                                        E0701
1                                                        E0702
2                                                        E0703
3                                                        E0704
4                                                        E1301
...                                                        ...
3076                                                        MD
3077                                                        UA
3078                                                        SC
3079                                                        SD
3080                                                         O

theme                                         \
sub_theme                               name
description The name of the local authority.
Variable                             LA_name
0                              Hartlepool UA
1                           Middlesbrough UA
2                      Redcar & Cleveland UA
3                        Stockton-on-Tees UA
4                              Darlington UA
...                                      ...
3076                  Metropolitan Districts
3077                     Unitary Authorities
3078                          Shire Counties
3079                         Shire Districts
3080                       Other Authorities

theme                                                                                                                                                                                   \
sub_theme                                                                                                                                                                          NaN
description The submission status. Takes one of three values: submitted, not submitted, or total. Totals are calculated, further information available on the Metadata - totals page.
Variable                                                                                                                                                                        status
0                                                    submitted
1                                                    submitted
2                                                    submitted
3                                                    submitted
4                                                    submitted
...                                                        ...
3076                                                     total
3077                                                     total
3078                                                     total
3079                                                     total
3080                                                     total

theme                                                                                                                                                                                                                                                                                                   \
sub_theme                                                                                                                                                                                                                                                                                        class
description The general classification of the local authority. A local authority's classification is related to the functions it carries out and how they are financed. More information on local authority types is available at https://www.gov.uk/guidance/local-government-structure-and-elections
Variable                                                                                                                                                                                                                                                                                      LA_class
0                                            Unitary Authority
1                                            Unitary Authority
2                                            Unitary Authority
3                                            Unitary Authority
4                                            Unitary Authority
...                                                        ...
3076                                              Met District
3077                                         Unitary Authority
3078                                              Shire County
3079                                            Shire District
3080                                                     Other

theme                                                                                                                                                                                                                                                                                         Subsidies  \
sub_theme                                                                                                                                                                                                                                                                                      subclass
description The detailed classification of the local authority. A local authority's classification is related to the functions it carries out and how they are financed. More information on local authority types is available at https://www.gov.uk/guidance/local-government-structure-and-elections
Variable                                                                                                                                                                                                                                                                                    LA_subclass
0                                            Unitary Authority
1                                            Unitary Authority
2                                            Unitary Authority
3                                            Unitary Authority
4                                            Unitary Authority
...                                                        ...
3076                                              Met District
3077                                         Unitary Authority
3078                                              Shire County
3079                                            Shire District
3080                                                     Other

theme                              Grants                          \
sub_theme                      grantindsg              grantinppg
description Dedicated Schools Grant (DSG)     Pupil Premium Grant
Variable          RG_grantindsg_tot_grant RG_grantinppg_tot_grant
0                                 42564.0                  3363.0
1                                 59739.0                  3966.0
2                                 41494.0                  1928.0
3                                 81821.0                  4515.0
4                                 29728.0                  1320.0
...                                   ...                     ...
3076                            6358721.0                435608.0
3077                            5436305.0                287940.0
3078                            9332326.0                402711.0
3079                                  0.0                     0.0
3080                                  0.0                     0.0

theme                                            ...  \
sub_theme                            grantinusm  ...
description Universal Infants Free School Meals  ...
Variable                RG_grantinusm_tot_grant  ...
0                                         242.0  ...
1                                         383.0  ...
2                                         247.0  ...
3                                         530.0  ...
4                                          94.0  ...
...                                         ...  ...
3076                                   108186.0  ...
3077                                    94188.0  ...
3078                                   173767.0  ...
3079                                        0.0  ...
3080                                        0.0  ...

theme                                                                        Capital  \
sub_theme                                                                    caploss
description External Trading Accounts - Capital Items - Loss on impairment of assets
Variable                                                             TSR_caploss_ext
0                                                          0.0
1                                                          0.0
2                                                        618.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                    -963.0
3077                                                    1136.0
3078                                                       0.0
3079                                                    8224.0
3080                                                     670.0

theme                                                                                 \
sub_theme
description Internal Trading Accounts - Capital Items - Loss on impairment of assets
Variable                                                             TSR_caploss_int
0                                                          0.0
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                     532.0
3077                                                      36.0
3078                                                       0.0
3079                                                    -548.0
3080                                                       0.0

theme                                                                                                                          \
sub_theme                                                                                                            capreval
description External Trading Accounts - Capital Items - Revaluations taken to surplus or deficit on the provision of services
Variable                                                                                                     TSR_capreval_ext
0                                                          0.0
1                                                       1213.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                  -10467.0
3077                                                  -13046.0
3078                                                      18.0
3079                                                  -18382.0
3080                                                       0.0

theme                                                                                                                          \
sub_theme
description Internal Trading Accounts - Capital Items - Revaluations taken to surplus or deficit on the provision of services
Variable                                                                                                     TSR_capreval_int
0                                                          0.0
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                    1733.0
3077                                                    1656.0
3078                                                     -19.0
3079                                                      -1.0
3080                                                       0.0

theme                                                                              \
sub_theme                                                                capgrant
description External Trading Accounts - Capital Items - Credit for capital grants
Variable                                                         TSR_capgrant_ext
0                                                          0.0
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                    -448.0
3077                                                   -1565.0
3078                                                       0.0
3079                                                    2663.0
3080                                                       0.0

theme                                                                              \
sub_theme
description Internal Trading Accounts - Capital Items - Credit for capital grants
Variable                                                         TSR_capgrant_int
0                                                          0.0
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                     -15.0
3077                                                     371.0
3078                                                       0.0
3079                                                     -47.0
3080                                                       0.0

theme                                                                                                              \
sub_theme                                                                                                 caprecs
description External Trading Accounts - Capital Items - Revenue Expenditure funded from Capital by Statute (RECS)
Variable                                                                                          TSR_caprecs_ext
0                                                          0.0
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                      28.0
3077                                                    1379.0
3078                                                       0.0
3079                                                    7203.0
3080                                                       0.0

theme                                                                                                              \
sub_theme
description Internal Trading Accounts - Capital Items - Revenue Expenditure funded from Capital by Statute (RECS)
Variable                                                                                          TSR_caprecs_int
0                                                          0.0
1                                                          0.0
2                                                          0.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                     438.0
3077                                                       2.0
3078                                                       0.0
3079                                                       0.0
3080                                                       0.0

theme                                                                                                    \
sub_theme                                                                                        capsum
description External Trading Accounts - Capital Items - Total Capital items (total of lines 931 to 936)
Variable                                                                                 TSR_capsum_ext
0                                                          0.0
1                                                       1953.0
2                                                        683.0
3                                                          0.0
4                                                          0.0
...                                                        ...
3076                                                   -6570.0
3077                                                     841.0
3078                                                      28.0
3079                                                   14574.0
3080                                                    9726.0

theme
sub_theme
description Internal Trading Accounts - Capital Items - Total Capital items (total of lines 931 to 936)
Variable                                                                                 TSR_capsum_int
0                                                          0.0
1                                                          0.0
2                                                          0.0

In [53]:
multi_desc.xs("LA_class", axis=1, level="Variable").squeeze().value_counts()

(Other / Unmapped, class, The general classification of the local authority. A local authority's classification is related to the functions it carries out and how they are financed. More information on local authority types is available at https://www.gov.uk/guidance/local-government-structure-and-elections)
Shire District       1315
Other                 668
Unitary Authority     413
Met District          259
London                238
Shire County          181
Eng                     7
Name: count, dtype: int64

In [54]:
multi_desc.columns.names

FrozenList(['theme', 'sub_theme', 'description', 'Variable'])

In [55]:
multi_desc.columns.levels

FrozenList([['Adjustments', 'Adult Social Care', 'Appropriations', 'Business Rates Support', 'COVID-19', 'Capital', 'Central Services', 'Children’s Social Care', 'Collection Fund Adjustments', 'Culture', 'Disbursements', 'Education', 'Environment', 'Equal Pay', 'Fire & Rescue', 'Grants', 'Housing', 'Housing Benefits', 'Housing Revenue Account', 'Income', 'Interest', 'Investment Properties', 'Levies', 'Net Current Expenditure', 'Net Revenue Expenditure', 'Other / Unmapped', 'Planning & Development', 'Police', 'Prior Year Adjustments', 'Provisions', 'Public Health', 'Reserves', 'Schools Funding', 'Subsidies', 'Total Service Expenditure', 'Trading', 'Transport'], ['ASC', 'LGF', 'accumul', 'adjexpcap', 'adjnce', 'appdsgadj', 'appfinadj', 'appresdsg', 'appresoth', 'appresothearA', 'appresothearB', 'appresothearC', 'appresph', 'appressch', 'appresunall', 'appunequal', 'asc', 'ascass', 'ascassadl', 'ascassold', 'asccmstad', 'asccmstadadl', 'asccmstadold', 'asccrasssfg', 'asccrasssfgadl', 'asccrasssfgold', 'asccvd19dsc', 'ascdsbcr', 'ascinf', 'ascinfadl', 'ascinfold', 'asclrnadl', 'asclrnold', 'ascmmradl', 'ascmmrold', 'ascmntadl', 'ascmntold', 'ascothnondsbcr', 'ascphyadl', 'ascphyold', 'ascsclasy', 'ascsclcrr', 'ascsclcrradl', 'ascsclcrrold', 'ascsclisl', 'ascsclsbs', 'ascsnsadl', 'ascsnsold', 'ascsvmem', 'asctot', 'asctotppe', 'brsupp', 'capdep', 'capgneqsbsjv', 'capgnfinderv', 'capgninvprp', 'capgnothinv', 'capgrant', 'caploss', 'caplosslnsbs', 'caplosslnsoth', 'caprecflex', 'caprecs', 'capreval', 'capsum', 'captot', 'cen', 'cencnt', 'cencntbrt', 'cencrn', 'cencrp', 'cencrtoth', 'cenemr', 'cennd', 'cenndcit', 'cenndcrtr', 'cenndcsrp', 'cenoth1', 'cenoth10', 'cenoth11', 'cenoth12', 'cenoth13', 'cenoth14', 'cenoth15', 'cenoth16', 'cenoth17', 'cenoth18', 'cenoth19', 'cenoth2', 'cenoth20', 'cenoth3', 'cenoth4', 'cenoth5', 'cenoth6', 'cenoth7', 'cenoth8', 'cenoth9', 'cenothsvmem', 'cenothtot', 'cenppe', ...], ['(adjusted) Other earmarked financial reserves level - end', '(adjusted) Other earmarked financial reserves level - start', 'A Local Government Finance code, which MHCLG uses internally to represent local authorities. These are unique to each local authority, similar to the ONS local authority code.', 'Additional Home to School Transport Funding', 'Additional discretionary grant fund for small businesses', 'Adult Social Care (ASC) Discharge Fund', 'Adult Social Care Grant', 'Adult Social Care Infection Control Fund - Round 1', 'Adult Social Care Infection Control Fund - Round 2', 'Adult Social Care Rapid Testing Fund', 'Adult Social Care Workplace Capacity Fund', 'Adult and Community Learning from Skills Funding Agency', 'Adult social care - memorandum item 'of which agency staff costs'', 'Appropriations to/from other earmarked financial reserves - of which 1 - other appropriations to other earmarked reserves', 'Appropriations to/from other earmarked financial reserves - of which 2 - amounts due to authority of expended retail and nursery business rates relief grant 2020-21', 'Appropriations to/from other earmarked financial reserves - of which 3 - share of COVID additional business rate relief grant 2021-22', 'BEIS Additional Restrictions Grant', 'COVID general funding grant tranche 1 (March 2020) carried forward - end', 'COVID general funding grant tranche 1 (March 2020) carried forward - start', 'COVID-19 Bus Services Support Grants (CBSSG), including Restart', 'COVID-19 LA Surge Funding', 'Capital Items - Credit for capital grants', 'Capital Items - Depreciation', 'Capital Items - Loss on impairment of assets', 'Capital Items - Revaluations taken to surplus or deficit on the provision of services', 'Capital Items - Revenue Expenditure funded from Capital by Statute (RECS)', 'Capital Items - Total Capital items (TOTAL OF LINES 931 TO 936)', 'Capital items - Gain/loss on fair value movements in investment properties', 'Capital items - Gain/loss on fair value movements in other investment assets', 'Capital items - Gain/loss on fair value movements on equity in subsidiaries, associates and joint ventures', 'Capital items - Gain/loss on financial derivatives', 'Capital items - Loss on impairment of loans to other parties (exc. Subsidiaries)', 'Capital items - Loss on impairment of loans to subsidiaries', 'Central services - memorandum item 'of which agency staff costs'', 'Children's social care- memorandum item 'of which agency staff costs'', 'Clinically Extremely Vulnerable (CEV) Funding', 'Community Champions Fund', 'Compliance and Enforcement Grant', 'Confirmation column indicating the RO suite of forms are completed on non-IAS19 and PFI Off-Balance Sheet basis. ', 'Cultural and related services - memorandum item 'of which agency staff costs'', 'DWP Covid Winter Support Grant Scheme', 'Dedicated Schools Grant (DSG)', 'Dedicated Schools Grant Adjustment Account level - end', 'Dedicated Schools Grant Adjustment Account level - start', 'Dedicated Schools Grant reserves level - end', 'Dedicated Schools Grant reserves level - start', 'Education Services Grant', 'Education services - memorandum item 'of which agency staff costs'', 'Emergency Active Travel Fund - Tranche 1 (CDEL and RDEL)', 'Employees - Accommodation within RSL stock', 'Employees - Accommodation within the authority's own stock (non-HRA)', 'Employees - Administration of financial support for repairs and improvements', 'Employees - Adult Social Care', 'Employees - Agricultural and fisheries services', 'Employees - Airports, harbours and toll facilities', 'Employees - Allotments', 'Employees - Animal and public health; infectious disease control', 'Employees - Any other type of temporary accommodation (including private landlord and not known)', 'Employees - Archives', 'Employees - Arts development and support', 'Employees - Assistive equipment and technology', 'Employees - BID ballots', 'Employees - Bed and breakfast hotels (including shared annexes)', 'Employees - Bed/breakfast accommodation', 'Employees - Building control', 'Employees - Bus lane enforcement', 'Employees - Business support', 'Employees - CCTV', 'Employees - CORPORATE AND DEMOCRATIC CORE', 'Employees - COVID-19 discharge costs', 'Employees - Care assessment and safeguarding* (previously named 'social care activities')', 'Employees - Cemetery, cremation and mortuary services', 'Employees - Central services', 'Employees - Children 5-19 public health programmes', 'Employees - Children Social Care', 'Employees - Children's social care - Asylum Seekers', 'Employees - Children's social care - Children Looked After', 'Employees - Children's social care - Family Support Services', 'Employees - Children's social care - Other children's and families services', 'Employees - Children's social care - Youth Justice', 'Employees - Children's social care - of which asylum seeking children who are looked after', 'Employees - Children's social care - of which fostering services', 'Employees - Children's social care - of which other', 'Employees - Children's social care - of which residential care', 'Employees - Children's social care: Safeguarding children and young people's services', 'Employees - Children's social care: Services for young people', 'Employees - Children's social care: Sure start children's centres and early years', 'Employees - Climate change costs', 'Employees - Coast protection', 'Employees - Commissioning, strategy and admin support* (previously named Commissioning and service delivery)', 'Employees - Community centres and public halls', 'Employees - Community development', 'Employees - Community fire safety', 'Employees - Conducting elections', 'Employees - Congestion charging', 'Employees - Conservation and listed buildings planning policy', 'Employees - Coroners' court services', 'Employees - Costs of unused shares of IT facilities and other assets', 'Employees - Council tax collection', 'Employees - Council tax discounts for prompt payment', ...], ['LA_LGF_code', 'LA_class', 'LA_name', 'LA_subclass', 'ONS_code', 'RG_ASC_spprt_grant', 'RG_edu_services_grant', 'RG_grantinaddsmlbus_tot_grant', 'RG_grantinascicf1_tot_grant', 'RG_grantinascicf2_tot_grant', 'RG_grantinascomspp_tot_grant', 'RG_grantinascrpdtst_tot_grant', 'RG_grantinascwrkcap_tot_grant', 'RG_grantinccbssg_tot_grant', 'RG_grantincdelrdel_tot_grant', 'RG_grantincev_tot_grant', 'RG_grantincmmchmp_tot_grant', 'RG_grantincmpenf_tot_grant', 'RG_grantindsfnd_tot_grant', 'RG_grantindsg_tot_grant', 'RG_grantindwpwntspp_tot_grant', 'RG_grantinfhs_tot_grant', 'RG_grantinfndgt_tot_grant', 'RG_grantinglat_tot_grant', 'RG_grantinhbs_tot_grant', 'RG_grantinhmlrdc_tot_grant', 'RG_grantinhmschtrns_tot_grant', 'RG_grantinibcf_tot_grant', 'RG_grantinilf_tot_grant', 'RG_grantinlaemrgfd_tot_grant', 'RG_grantinlasrg_tot_grant', 'RG_grantinlclelc_tot_grant', 'RG_grantinlcts_tot_grant', 'RG_grantinlrrg_tot_grant', 'RG_grantinlts_tot_grant', 'RG_grantinmkt_tot_grant', 'RG_grantinnhb_tot_grant', 'RG_grantinnxtstpsacc_tot_grant', 'RG_grantinoth_tot_grant', 'RG_grantinoutmgtfnd_tot_grant', 'RG_grantinpfi_tot_grant', 'RG_grantinph_tot_grant', 'RG_grantinpolup_tot_grant', 'RG_grantinppg_tot_grant', 'RG_grantinrecretasc_tot_grant', 'RG_grantinrghslp_tot_grant', 'RG_grantinrophgst_tot_grant', 'RG_grantinrsd_tot_grant', 'RG_grantinsbgfrhlgf_tot_grant', 'RG_grantinscs_tot_grant', 'RG_grantinslfiso_tot_grant', 'RG_grantinsrvs_tot_grant', 'RG_grantinsupptrniosios_tot_grant', 'RG_grantintot_tot_grant', 'RG_grantintsttrc_tot_grant', 'RG_grantinusm_tot_grant', 'RG_grantinwelbck_tot_grant', 'RG_grantinwp_tot_grant', 'RG_grantmmdsb1_tot_grant', 'RG_grantmmdsb2_tot_grant', 'RG_grantmmdsb3_tot_grant', 'RG_grantmmdsb4_tot_grant', 'RG_grantoutacomm_tot_grant', 'RG_grantouthbhreb_tot_grant', 'RG_grantouthbnreb_tot_grant', 'RG_grantouthbrent_tot_grant', 'RG_grantoutoth_tot_grant', 'RG_grantoutsixth_tot_grant', 'RG_grantouttot_tot_grant', 'RG_granttot_tot_grant', 'RO1_eduerl_empl', 'RO1_eduerl_net_cur_exp', 'RO1_eduerl_oth_inc', 'RO1_eduerl_run_exp', 'RO1_eduerl_sfc', 'RO1_eduerl_tot_exp', 'RO1_eduerl_tot_inc', 'RO1_eduoth_empl', 'RO1_eduoth_net_cur_exp', 'RO1_eduoth_oth_inc', 'RO1_eduoth_run_exp', 'RO1_eduoth_sfc', 'RO1_eduoth_tot_exp', 'RO1_eduoth_tot_inc', 'RO1_eduprm_empl', 'RO1_eduprm_net_cur_exp', 'RO1_eduprm_oth_inc', 'RO1_eduprm_run_exp', 'RO1_eduprm_sfc', 'RO1_eduprm_tot_exp', 'RO1_eduprm_tot_inc', 'RO1_edupst_empl', 'RO1_edupst_net_cur_exp', 'RO1_edupst_oth_inc', 'RO1_edupst_run_exp', 'RO1_edupst_sfc', 'RO1_edupst_tot_exp', 'RO1_edupst_tot_inc', 'RO1_eduscn_empl', 'RO1_eduscn_net_cur_exp', ...]])

In [56]:

df_lb = multi_desc[
    multi_desc.xs("LA_class", level="Variable", axis=1).squeeze().astype(str).str.strip().eq("London")
]

In [57]:
df_lb

theme       Other / Unmapped                                \
sub_theme             ending                          code
description             Year The ONS local authority code.
Variable         year_ending                      ONS_code
263                     2024                     E09000001
264                     2024                     E09000002
265                     2024                     E09000003
266                     2024                     E09000004
267                     2024                     E09000005
...                      ...                           ...
2951                    2018                     E09000030
2952                    2018                     E09000031
2953                    2018                     E09000032
2954                    2018                     E09000033
3075                    2018                           E09

theme                                                                                                                                                                                        \
sub_theme                                                                                                                                                                               LGF
description A Local Government Finance code, which MHCLG uses internally to represent local authorities. These are unique to each local authority, similar to the ONS local authority code.
Variable                                                                                                                                                                        LA_LGF_code
263                                                      E5010
264                                                      E5030
265                                                      E5031
266                                                      E5032
267                                                      E5033
...                                                        ...
2951                                                     E5020
2952                                                     E5049
2953                                                     E5021
2954                                                     E5022
3075                                                        LB

theme                                         \
sub_theme                               name
description The name of the local authority.
Variable                             LA_name
263                           City of London
264                       Barking & Dagenham
265                                   Barnet
266                                   Bexley
267                                    Brent
...                                      ...
2951                           Tower Hamlets
2952                          Waltham Forest
2953                              Wandsworth
2954                             Westminster
3075                         London Boroughs

theme                                                                                                                                                                                   \
sub_theme                                                                                                                                                                          NaN
description The submission status. Takes one of three values: submitted, not submitted, or total. Totals are calculated, further information available on the Metadata - totals page.
Variable                                                                                                                                                                        status
263                                                  submitted
264                                                  submitted
265                                                  submitted
266                                                  submitted
267                                                  submitted
...                                                        ...
2951                                                 submitted
2952                                                 submitted
2953                                                 submitted
2954                                                 submitted
3075                                                     total

theme                                                                                                                                                                                                                                                                                                   \
sub_theme                                                                                                                                                                                                                                                                                        class
description The general classification of the local authority. A local authority's classification is related to the functions it carries out and how they are financed. More information on local authority types is available at https://www.gov.uk/guidance/local-government-structure-and-elections
Variable                                                                                                                                                                                                                                                                                      LA_class
263                                                     London
264                                                     London
265                                                     London
266                                                     London
267                                                     London
...                                                        ...
2951                                                    London
2952                                                    London
2953                                                    London
2954                                                    London
3075                                                    London

theme                                                                                                                                                                                                                                                                                         Subsidies  \
sub_theme                                                                                                                                                                                                                                                                                      subclass
description The detailed classification of the local authority. A local authority's classification is related to the functions it carries out and how they are financed. More information on local authority types is available at https://www.gov.uk/guidance/local-government-structure-and-elections
Variable                                                                                                                                                                                                                                                                                    LA_subclass
263                                                     London
264                                                     London
265                                                     London
266                                                     London
267                                                     London
...                                                        ...
2951                                                    London
2952                                                    London
2953                                                    London
2954                                                    London
3075                                                    London

theme                              Grants                          \
sub_theme                      grantindsg              grantinppg
description Dedicated Schools Grant (DSG)     Pupil Premium Grant
Variable          RG_grantindsg_tot_grant RG_grantinppg_tot_grant
263                                3942.0                   101.0
264                              264128.0                 12482.0
265                              265807.0                  9827.0
266                               91657.0                  1554.0
267                              220859.0                  6522.0
...                                   ...                     ...
2951                             281803.0                 19947.0
2952                             169153.0                  8271.0
2953                             156680.0                  7811.0
2954                              85111.0                  4742.0
3075                            5388835.0                282825.0

theme                                            ...  \
sub_theme                            grantinusm  ...
description Universal Infants Free School Meals  ...
Variable                RG_grantinusm_tot_grant  ...
263                                        27.0  ...
264                                      2851.0  ...
265                                      3480.0  ...
266                                       908.0  ...
267                                      3078.0  ...
...                                         ...  ...
2951                                     2735.0  ...
2952                                     2173.0  ...
2953                                     2488.0  ...
2954                                      228.0  ...
3075                                    68780.0  ...

theme                                                                        Capital  \
sub_theme                                                                    caploss
description External Trading Accounts - Capital Items - Loss on impairment of assets
Variable                                                             TSR_caploss_ext
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                                 \
sub_theme
description Internal Trading Accounts - Capital Items - Loss on impairment of assets
Variable                                                             TSR_caploss_int
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                                                                          \
sub_theme                                                                                                            capreval
description External Trading Accounts - Capital Items - Revaluations taken to surplus or deficit on the provision of services
Variable                                                                                                     TSR_capreval_ext
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                                                                          \
sub_theme
description Internal Trading Accounts - Capital Items - Revaluations taken to surplus or deficit on the provision of services
Variable                                                                                                     TSR_capreval_int
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                              \
sub_theme                                                                capgrant
description External Trading Accounts - Capital Items - Credit for capital grants
Variable                                                         TSR_capgrant_ext
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                              \
sub_theme
description Internal Trading Accounts - Capital Items - Credit for capital grants
Variable                                                         TSR_capgrant_int
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                                                              \
sub_theme                                                                                                 caprecs
description External Trading Accounts - Capital Items - Revenue Expenditure funded from Capital by Statute (RECS)
Variable                                                                                          TSR_caprecs_ext
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                                                              \
sub_theme
description Internal Trading Accounts - Capital Items - Revenue Expenditure funded from Capital by Statute (RECS)
Variable                                                                                          TSR_caprecs_int
263                                                        0.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                       0.0

theme                                                                                                    \
sub_theme                                                                                        capsum
description External Trading Accounts - Capital Items - Total Capital items (total of lines 931 to 936)
Variable                                                                                 TSR_capsum_ext
263                                                     1775.0
264                                                        0.0
265                                                        0.0
266                                                        0.0
267                                                        0.0
...                                                        ...
2951                                                       0.0
2952                                                       0.0
2953                                                       0.0
2954                                                       0.0
3075                                                     677.0

theme
sub_theme
description Internal Trading Accounts - Capital Items - Total Capital items (total of lines 931 to 936)
Variable                                                                                 TSR_capsum_int
263                                                        0.0
264                                                        0.0
265                                                        0.0

In [58]:
df_lb.to_csv("../myenv/capstone data/Revenue.csv", index=False)

In [59]:
# If you want to inspect which statuses exist
status_col = df_lb.loc[:, df_lb.columns.get_level_values("Variable") == "status"]

# It's usually a single column, so squeeze it down to a Series
status_series = status_col.squeeze()

# Now check the distribution
print(status_series.value_counts())

(Other / Unmapped, nan, The submission status. Takes one of three values: submitted, not submitted, or total. Totals are calculated, further information available on the Metadata - totals page. , status)
submitted    231
total          7
Name: count, dtype: int64