In [ ]:

import xml.etree.ElementTree as ET
import pandas as pd

# 1. Load your XML (make sure 'capitalgrowth-london.xml' is in your notebook dir)
tree = ET.parse('../myenv/capstone data/capitalgrowth-london.xml')
root = tree.getroot()

# 2. Build a list of dicts, one per <marker>
records = []
for m in root.findall('marker'):
    # Grab every attribute on this element
    attrs = m.attrib.copy()
    # Convert lat/lng to floats
    if 'lat' in attrs:  attrs['lat'] = float(attrs['lat'])
    if 'lng' in attrs:  attrs['lng'] = float(attrs['lng'])
    records.append(attrs)

# 3. Turn into a DataFrame
df = pd.DataFrame(records)

# 4. Quick sanity‐check
print(df.shape, "markers loaded")
df.head(5)

(388, 48) markers loaded

,space_id,project_decs,resultsString,image,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,corp_day_mon,corp_day_tue,corp_day_wed,corp_day_thu,corp_day_fri,corp_day_sat,corp_day_sun,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name
0,6200,5 raised beda and a pond.,Gardens 1 to 388 of 388,6200_1552296525.jpg,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN
1,309,Sutton Community Farm is a community-owned far...,Gardens 1 to 388 of 388,309_1552667884.jpg,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,1,0,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,11522,We have a regular food growing and volunteerin...,Gardens 1 to 388 of 388,11522_1552489595.jpg,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,13116,Applegarth Academy has a small but well equipp...,Gardens 1 to 388 of 388,,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,13156,We have a community allotment off Colston Aven...,Gardens 1 to 388 of 388,,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN

In [73]:
import pandas as pd

# allow pandas to print all columns when showing df
pd.set_option('display.max_columns', None)

# now .head() or just typing `df` will show every column
df.head(20)

,space_id,project_decs,resultsString,image,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,corp_day_mon,corp_day_tue,corp_day_wed,corp_day_thu,corp_day_fri,corp_day_sat,corp_day_sun,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name
0,6200,5 raised beda and a pond.,Gardens 1 to 388 of 388,6200_1552296525.jpg,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN
1,309,Sutton Community Farm is a community-owned far...,Gardens 1 to 388 of 388,309_1552667884.jpg,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,1,0,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,11522,We have a regular food growing and volunteerin...,Gardens 1 to 388 of 388,11522_1552489595.jpg,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,13116,Applegarth Academy has a small but well equipp...,Gardens 1 to 388 of 388,,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,13156,We have a community allotment off Colston Aven...,Gardens 1 to 388 of 388,,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
5,5828,Our garden is made up of 6 garden&#39;rooms&#...,Gardens 1 to 388 of 388,5828_1555699631.jpg,CR0 1BB,1,Park Hill Park Community Garden,51.368103,-0.092325,4,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN
6,13424,MHA The Wilderness is a 5 acre heritage woodla...,Gardens 1 to 388 of 388,13424_1739550849.jpg,CR9 5AL,1,MHA The Wilderness,51.371498,-0.053079,1,1,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
7,12469,Our aim is to create a community food growing ...,Gardens 1 to 388 of 388,12469_1623844308.jpg,KT5 9AL,1,Fishponds Community Garden,51.387661,-0.292006,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
8,3,Expanding on a food growing space to create ne...,Gardens 1 to 388 of 388,3_1681853072.jpg,SM4 6RW,1,May Project Food Growing project,51.388691,-0.183618,4,0,0,1,,,,,,,,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
9,2792,&#13;&#10;<p>This project&nbsp;encourages comm...,Gardens 1 to 388 of 388,,BR2 9LW,1,Southlands Road Allotments,51.395630,0.037256,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN
10,12069,A community orchard containing around 40 diffe...,Gardens 1 to 388 of 388,12069_1606137049.jpg,CR4 3AL,1,Mitcham Community Orchard and Gardens,51.406338,-0.169348,1,1,0,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN
11,23,,,,SW19 2ST,1,Phipps Bridge Community Garden,51.407524,-0.183344,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,322,Merton
12,5974,,,,SW19 2RR,8,Deen City Farm,51.408070,-0.185497,4,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,322,Merton
13,13077,,,,SW165UQ,7,Woodmansterne School Farm,51.411224,-0.134356,1,1,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,320,Lambeth
14,5980,,,,CR4 3LB,2,Tamworth Farm Allotments,51.414364,-0.162648,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,322,Merton
15,6405,,,,SW19 3QT,1,Wimbledon Guild Community Garden,51.416611,-0.206714,1,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,322,Merton
16,13147,,,,CR4 2ET,6,Plot 1 - North Mitcham Plot Owners Association...,51.417137,-0.147716,1,1,,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,322,Merton
17,13224,,,,SE19 3ST,7,Rockmount Primary School,51.418633,-0.091992,3,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,307,Croydon
18,13104,,,,SE19 2BA,1,Invisible Palace,51.420059,-0.078123,1,1,,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,305,Bromley
19,13161,,,,SE270EU,1,Holderness Way Communal Garden,51.423813,-0.103942,3,0,,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,320,Lambeth

In [74]:
df['icon'].value_counts()

icon
1    181
3    109
4     98
Name: count, dtype: int64

Science Garden, icon is 3, displayed on website as active. Sutton Community Farm, icon is 1, displayed as volunteers needed. GOOD FOOD MATTERS, icon is 4, displayed as inactive.

corp_day_XXX is used to show which days of the week the space is open for volunteering.

In [75]:

# 5. Drop columns we won’t need
df = df.drop(columns=['resultsString','image'], errors='ignore')

# 6. Strip whitespace from key text fields
for col in ['space_postcode','space_name','project_decs']:
    if col in df:
        df[col] = df[col].astype(str).str.strip()

# 7. Coerce some flags to numeric (and fill NaNs)
for col in ['vol_required','in_next_event','allotmentsMarker']:
    if col in df:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)

# 8. Rename corp_day_* to weekdays
old_days = ['corp_day_mon','corp_day_tue','corp_day_wed',
            'corp_day_thu','corp_day_fri','corp_day_sat','corp_day_sun']
new_days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
rename_map = {o:n for o,n in zip(old_days,new_days) if o in df}
df = df.rename(columns=rename_map)
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,1,0,1,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN

In [76]:
missing = df[new_days].isna().sum()
missing

Monday       0
Tuesday      0
Wednesday    0
Thursday     0
Friday       0
Saturday     0
Sunday       0
dtype: int64

In [77]:


# 1. Replace blanks with '0'
df[new_days] = df[new_days].replace('', '0')

# 2. Coerce to numeric → fill NaN → int
df[new_days] = df[new_days].apply(pd.to_numeric, errors='coerce') \
                           .fillna(0) \
                           .astype(int)

# 3. Convert to bool
df[new_days] = df[new_days].astype(bool)

# Quick sanity‐check
print(df[new_days].head())
for d in new_days:
    print(d, df[d].unique())

   Monday  Tuesday  Wednesday  Thursday  Friday  Saturday  Sunday
0   False    False      False     False   False     False   False
1    True    False       True      True   False      True   False
2   False    False      False     False    True     False   False
3   False    False      False     False   False     False   False
4   False    False      False     False   False     False   False
Monday [False  True]
Tuesday [False  True]
Wednesday [False  True]
Thursday [False  True]
Friday [False  True]
Saturday [False  True]
Sunday [False  True]

Still need to find out spacetype number meanings.

In [78]:
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,0,0,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,1,0,True,False,True,True,False,True,False,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,0,1,False,False,False,False,True,False,False,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,0,0,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,0,1,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN

In [79]:
df['vol_days_count'] = df[new_days].sum(axis=1)
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name,vol_days_count
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,0,0,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN,0
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,1,0,True,False,True,True,False,True,False,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,4
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,0,1,False,False,False,False,True,False,False,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,0,0,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,0,1,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0

In [80]:
df['in_next_event'] = df['in_next_event'].astype(bool)

In [81]:
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name,vol_days_count
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,False,0,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN,0
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,True,0,True,False,True,True,False,True,False,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,4
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,False,1,False,False,False,False,True,False,False,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,False,0,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,False,1,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0

In [82]:
df['allotmentsMarker'].value_counts()

allotmentsMarker
1    286
0    102
Name: count, dtype: int64

In [83]:
df['allotmentsMarker'] = df['allotmentsMarker'].astype(bool)    
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name,vol_days_count
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,NaN,NaN,0
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,True,False,True,False,True,True,False,True,False,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,4
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,False,True,False,False,False,False,True,False,False,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,False,True,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0

In [84]:
event_cols = [c for c in df if c.startswith('eventDay')]

# 1. Replace any empty‐string with '0' (so it can be parsed as numeric)
df[event_cols] = df[event_cols].replace('', '0')

# 2. Convert each column to numeric → fill NaNs → int
df[event_cols] = df[event_cols] \
                    .apply(lambda ser: pd.to_numeric(ser, errors='coerce')) \
                    .fillna(0) \
                    .astype(int)
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name,vol_days_count
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,True,False,True,False,True,True,False,True,False,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,4
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,False,True,False,False,False,False,True,False,False,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,False,True,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0

In [85]:

df['event_days_count'] = df[event_cols].sum(axis=1)
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,eventDay11,eventDay12,eventDay13,eventDay14,eventDay15,eventDay16,eventDay17,eventDay18,eventDay19,eventDay20,eventDay21,eventDay22,eventDay23,eventDay24,eventDay25,eventDay26,eventDay27,eventDay28,eventDay29,eventDay30,eventDay1,eventDay2,eventDay3,eventDay4,eventDay5,eventDay6,poly_id,poly_name,vol_days_count,event_days_count
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,True,False,True,False,True,True,False,True,False,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,4,1
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,False,True,False,False,False,False,True,False,False,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,1
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,False,False,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,False,True,False,False,False,False,False,False,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0

In [86]:
df = df.drop(columns=event_cols)
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,True,False,True,False,True,True,False,True,False,NaN,NaN,4,1
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,False,True,False,False,False,False,True,False,False,NaN,NaN,1,1
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0

In [87]:
df['icon'] = df['icon'].str.strip()

In [88]:
# 1. Define your mapping
icon_map = {
    '3': 'active',
    '1': 'volunteers wanted',
    '4': 'inactive'
}

# 2. Apply it
df['status'] = df['icon'].map(icon_map).fillna('unknown')
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,icon,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,3,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,1,True,False,True,False,True,True,False,True,False,NaN,NaN,4,1,volunteers wanted
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,4,1,False,True,False,False,False,False,True,False,False,NaN,NaN,1,1,inactive
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,3,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted

In [89]:
df = df.drop(columns=['icon'])
df.head()

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,True,False,True,False,True,True,False,True,False,NaN,NaN,4,1,volunteers wanted
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,1,False,True,False,False,False,False,True,False,False,NaN,NaN,1,1,inactive
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted

In [90]:
df['space_type'].value_counts()

space_type
1    240
7     46
6     46
5     31
8     19
2      3
3      2
4      1
Name: count, dtype: int64

In [91]:
type_1 = df[df['space_type'].str.strip() == '1'].reset_index(drop=True)
type_1.head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,1,False,True,False,False,False,False,True,False,False,NaN,NaN,1,1,inactive
1,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted
2,5828,Our garden is made up of 6 garden&#39;rooms&#...,CR0 1BB,1,Park Hill Park Community Garden,51.368103,-0.092325,1,False,True,False,False,False,False,False,True,False,NaN,NaN,1,0,inactive
3,13424,MHA The Wilderness is a 5 acre heritage woodla...,CR9 5AL,1,MHA The Wilderness,51.371498,-0.053079,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted
4,12469,Our aim is to create a community food growing ...,KT5 9AL,1,Fishponds Community Garden,51.387661,-0.292006,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,inactive
5,3,Expanding on a food growing space to create ne...,SM4 6RW,1,May Project Food Growing project,51.388691,-0.183618,0,False,True,False,False,False,False,False,False,False,NaN,NaN,0,1,inactive
6,2792,&#13;&#10;<p>This project&nbsp;encourages comm...,BR2 9LW,1,Southlands Road Allotments,51.395630,0.037256,0,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,active
7,12069,A community orchard containing around 40 diffe...,CR4 3AL,1,Mitcham Community Orchard and Gardens,51.406338,-0.169348,1,False,True,False,False,False,True,True,True,False,NaN,NaN,3,1,volunteers wanted
8,23,,SW19 2ST,1,Phipps Bridge Community Garden,51.407524,-0.183344,1,False,True,False,False,True,False,False,False,False,322,Merton,1,1,volunteers wanted
9,6405,,SW19 3QT,1,Wimbledon Guild Community Garden,51.416611,-0.206714,1,False,True,True,False,False,True,False,True,False,322,Merton,3,1,volunteers wanted
10,13104,,SE19 2BA,1,Invisible Palace,51.420059,-0.078123,1,False,True,False,False,False,False,True,False,False,305,Bromley,1,0,volunteers wanted
11,13161,,SE270EU,1,Holderness Way Communal Garden,51.423813,-0.103942,0,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,active
12,6359,,KT2 5BD,1,Canbury Community Garden,51.424736,-0.306469,1,False,True,False,False,False,False,False,True,True,319,Kingston upon Thames,2,1,volunteers wanted
13,13244,,SE19 1EA,1,Norwood Park community gardens,51.425819,-0.093267,0,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,active
14,482,,KT2 5LX,1,Parkfields Community Garden,51.426792,-0.291764,1,False,True,False,False,True,False,False,True,True,319,Kingston upon Thames,3,0,volunteers wanted
15,12001,,BR1 5RD,1,The Plot,51.428020,-0.005432,1,False,True,False,False,False,False,False,False,True,321,Lewisham,1,1,volunteers wanted
16,12036,,SW16 2BP,1,Railside Community Garden,51.428528,-0.124694,1,False,True,False,False,False,False,False,True,False,320,Lambeth,1,1,inactive
17,13362,,SW16 1SH,1,Furzedown Project&#39;s Furzedown Farmers&#39;...,51.429619,-0.143726,1,False,True,False,True,False,False,False,False,False,322,Merton,1,0,volunteers wanted
18,13461,,se21 8qn,1,Kingswood Arts Community Garden,51.430489,-0.081774,1,False,True,False,True,False,True,False,False,False,326,Southwark,2,0,volunteers wanted
19,487,,SE26 4AB,1,Sydenham Garden Food Growing Space,51.431011,-0.043047,1,True,True,False,True,True,True,True,False,False,321,Lewisham,4,1,volunteers wanted

In [92]:
print(df['space_type'].dtype)
print(df['space_type'].unique())

object
['7' '8' '1' '2' '6' '5' '3' '4']

In [93]:

# 2. Build a regex filter for words beginning “comm”
pattern = r'\bcomm\w*'

# 3. Create a boolean column if either field matches
type_1['has_comm'] = (
    type_1['project_decs'].str.contains(pattern, case=False, na=False)
  | type_1['space_name'].str.contains(pattern, case=False, na=False)
)
print(type_1['has_comm'].value_counts())
type_1[type_1['has_comm']].head()

has_comm
False    145
True      95
Name: count, dtype: int64

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status,has_comm
1,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted,True
2,5828,Our garden is made up of 6 garden&#39;rooms&#...,CR0 1BB,1,Park Hill Park Community Garden,51.368103,-0.092325,1,False,True,False,False,False,False,False,True,False,NaN,NaN,1,0,inactive,True
3,13424,MHA The Wilderness is a 5 acre heritage woodla...,CR9 5AL,1,MHA The Wilderness,51.371498,-0.053079,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted,True
4,12469,Our aim is to create a community food growing ...,KT5 9AL,1,Fishponds Community Garden,51.387661,-0.292006,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,inactive,True
5,3,Expanding on a food growing space to create ne...,SM4 6RW,1,May Project Food Growing project,51.388691,-0.183618,0,False,True,False,False,False,False,False,False,False,NaN,NaN,0,1,inactive,True

In [94]:
type_1[~type_1['has_comm']].head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status,has_comm
0,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,1,False,True,False,False,False,False,True,False,False,NaN,NaN,1,1,inactive,False
10,13104,,SE19 2BA,1,Invisible Palace,51.420059,-0.078123,1,False,True,False,False,False,False,True,False,False,305,Bromley,1,0,volunteers wanted,False
15,12001,,BR1 5RD,1,The Plot,51.428020,-0.005432,1,False,True,False,False,False,False,False,False,True,321,Lewisham,1,1,volunteers wanted,False
17,13362,,SW16 1SH,1,Furzedown Project&#39;s Furzedown Farmers&#39;...,51.429619,-0.143726,1,False,True,False,True,False,False,False,False,False,322,Merton,1,0,volunteers wanted,False
19,487,,SE26 4AB,1,Sydenham Garden Food Growing Space,51.431011,-0.043047,1,True,True,False,True,True,True,True,False,False,321,Lewisham,4,1,volunteers wanted,False
20,6442,,SE21 8DE,1,Tritton Vale Pocket Garden,51.432541,-0.093630,1,False,True,True,True,True,True,True,True,True,320,Lambeth,7,0,volunteers wanted,False
22,12902,,SE6 1UA,1,Forster Memorial Park Sensory Garden,51.433231,-0.005438,1,False,True,False,False,False,False,True,False,False,321,Lewisham,1,0,volunteers wanted,False
24,5903,,SE6 4PL,1,Wild Cat Wilderness,51.436893,-0.027851,1,False,True,False,False,False,True,True,True,False,321,Lewisham,3,1,volunteers wanted,False
26,13426,,SW17 0YF,1,Share Garden,51.438549,-0.173943,0,False,True,False,False,False,False,False,False,False,330,Wandsworth,0,0,active,False
27,11704,,SE24 9AQ,1,South London Botanical Institute,51.441414,-0.105211,1,False,True,False,True,True,False,False,False,False,320,Lambeth,2,0,volunteers wanted,False
28,13132,,SE9 2EL,1,Roots4life,51.442280,0.066767,1,False,True,True,False,True,False,False,False,False,309,Greenwich,2,1,volunteers wanted,False
32,12982,,SW2 2AL,1,Roupell Park Pocket Garden,51.449814,-0.120194,0,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,inactive,False
33,6028,,SW18 3JE,1,The Paradise Cooperative,51.450184,-0.175676,1,True,True,False,False,False,False,False,False,True,330,Wandsworth,1,1,volunteers wanted,False
34,13129,,SE136QP,1,Lewisham Park Herbal Plot,51.453098,-0.011304,1,False,True,False,True,False,False,True,True,False,305,Bromley,3,0,volunteers wanted,False
35,6468,,SW2 5DA,1,Windmill Gardens,51.453293,-0.123673,1,True,True,False,True,False,False,False,True,False,320,Lambeth,2,1,volunteers wanted,False
36,1828,,SW2,1,Brixton Flour,51.453674,-0.123693,1,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,volunteers wanted,False
40,13249,,SW2 1BE,1,Effra Green Streets,51.457340,-0.111193,1,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,volunteers wanted,False
41,13097,,SW2 1NQ,1,The Brixton Orchard,51.459049,-0.116514,1,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,volunteers wanted,False
42,26,,SW15 5PJ,1,RU Outdoors / Growhampton,51.459572,-0.249415,0,False,True,False,False,False,False,False,False,False,330,Wandsworth,0,1,active,False
44,11772,,SE4 2BL,1,Frendsbury Gardens,51.461166,-0.043761,1,False,True,False,False,False,False,False,True,False,326,Southwark,1,1,volunteers wanted,False

In [95]:
type_7 = df[df['space_type'].str.strip() == '7'].reset_index(drop=True)
type_7.head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active
1,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active
2,13077,,SW165UQ,7,Woodmansterne School Farm,51.411224,-0.134356,1,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,volunteers wanted
3,13224,,SE19 3ST,7,Rockmount Primary School,51.418633,-0.091992,0,False,False,False,False,False,False,False,False,False,307,Croydon,0,0,active
4,13181,,DA15 7EB,7,Benedict House Prep School,51.427948,0.101045,0,False,False,False,False,False,False,False,False,False,303,Bexley,0,1,active
5,6214,,SE27 9BZ,7,The Elmgreen School,51.438564,-0.103850,0,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,active
6,13355,,SE12 0SJ,7,St Winifred&#39;s Catholic Primary,51.447674,0.010224,0,False,False,False,False,False,False,False,False,False,321,Lewisham,0,0,active
7,13368,,TW14 9XP,7,Westmacott Orchard,51.446983,-0.419585,0,False,False,False,False,False,False,False,False,False,316,Hounslow,0,0,active
8,12112,,SW8 3EH,7,Heathbrook Primary School Wildlife Garden,51.469215,-0.142910,1,False,False,False,False,False,False,False,True,False,320,Lambeth,1,1,inactive
9,12868,,SE4 1DF,7,Myatt Garden Primary School Allotment,51.470181,-0.031645,1,False,False,True,True,False,False,False,False,False,321,Lewisham,2,0,inactive
10,12733,,SE5 7TF,7,St George&#39;s CoE Primary School,51.480133,-0.084341,1,False,False,False,False,False,False,False,True,False,326,Southwark,1,1,volunteers wanted
11,3022,,SE7 8HX,7,Growing Green,51.481812,0.045877,1,False,False,False,False,False,False,False,False,False,309,Greenwich,0,0,volunteers wanted
12,4106,,sw10 0ay,7,Food in our secret garden,51.484154,-0.177963,0,True,False,False,False,False,False,False,False,False,318,Kensington and Chelsea,0,1,active
13,1503,,SE10 0DZ,7,Christchurch School Community Garden,51.486786,0.006062,1,True,False,False,False,False,False,True,True,False,309,Greenwich,2,1,volunteers wanted
14,12044,,SE17 2JY,7,Edible Rotherhithe &amp; Surrey Square School ...,51.488766,-0.083073,0,False,False,True,False,True,False,False,False,False,326,Southwark,2,1,active
15,12704,,TW7 5DB,7,Bolder Academy,51.488659,-0.336567,1,False,False,False,False,False,False,False,False,False,316,Hounslow,0,0,inactive
16,12943,,SE1 1AF,7,Charles Dickens Forest School Garden and Nursery,51.501369,-0.096282,0,False,False,False,False,False,False,False,False,False,326,Southwark,0,0,inactive
17,12535,,SE1 3TD,7,Snowsfields Primary School Garden,51.501511,-0.083850,1,False,False,False,False,False,False,False,False,False,326,Southwark,0,0,volunteers wanted
18,13352,,E16 2AW,7,Britannia Village Primary School Ecogarden &am...,51.503796,0.025311,0,False,False,False,False,False,False,False,False,False,323,Newham,0,0,active
19,13299,,E6 5JG,7,The Hub garden,51.514385,0.055398,0,False,False,False,False,False,False,False,False,False,323,Newham,0,0,active

Space type 7 is schools/educational

In [96]:
type_6 = df[df['space_type'].str.strip() == '6'].reset_index(drop=True)
type_6.head(50)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,13147,,CR4 2ET,6,Plot 1 - North Mitcham Plot Owners Association...,51.417137,-0.147716,1,False,True,True,False,False,False,True,True,False,322,Merton,3,0,volunteers wanted
1,13072,,BR1 5RD,6,Grow Lewisham,51.427834,-0.004952,1,False,True,False,False,False,False,False,False,False,305,Bromley,0,0,inactive
2,13230,,SE6 3SP,6,Firhill South Allotments,51.429977,-0.027776,1,True,True,False,False,False,False,False,False,False,321,Lewisham,0,3,volunteers wanted
3,13182,,SW2 3HL,6,Hillside Gardens,51.437607,-0.115545,1,False,True,False,False,False,False,False,False,False,320,Lambeth,0,0,volunteers wanted
4,13418,,SE6 2HR,6,Weavers Estate,51.442570,-0.013867,0,False,True,False,False,False,False,False,False,False,321,Lewisham,0,0,active
5,13118,,TW10 7HA,6,Plot 46 Walnut Tree Meadow Allotments,51.442696,-0.316385,0,False,True,False,False,False,False,False,False,False,325,Richmond upon Thames,0,0,active
6,13108,,SE22 0AF,6,Melford gardens and allotments,51.444889,-0.067929,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,active
7,12260,,SE23 3NP,6,AFRIL Allotment of Refuge (AOR),51.449917,-0.047837,1,False,True,False,True,False,False,True,True,False,326,Southwark,3,1,volunteers wanted
8,13105,,SE22 0BZ,6,Friern Road Allotment,51.453880,-0.067679,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,active
9,13462,,SE5 8DR,6,Champion Hill Community Garden,51.463917,-0.084807,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,active
10,13101,,Tw14 0AN,6,Heron Way Community Allotment,51.463833,-0.412168,1,False,True,True,True,True,True,True,True,True,316,Hounslow,7,0,volunteers wanted
11,12830,,SE5 7HD,6,Southampton Way Community Garden,51.476803,-0.080395,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,inactive
12,11756,,SE5 7TH,6,Parent Action Allotment,51.478889,-0.091152,1,False,True,False,False,False,True,False,False,False,326,Southwark,1,0,volunteers wanted
13,12441,,SE5 7NG,6,Caspian Street Allotments,51.478909,-0.091926,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,active
14,12821,,SE15 1BG,6,Ledbury Community Garden,51.479652,-0.064141,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,inactive
15,12831,,SE5 0PP,6,Brandon 3TRA Allotments,51.479893,-0.101448,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,inactive
16,13082,,SE1 5GG,6,Tate Stores Wellbeing Garden,51.492455,-0.080651,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,active
17,13325,,SE1 4DL,6,Tabard Gardens Allotment,51.498634,-0.087250,1,False,True,False,False,False,False,True,True,True,326,Southwark,3,0,volunteers wanted
18,12677,,SE1 3DQ,6,Purbrook Gardeners,51.498653,-0.078423,0,False,True,False,False,False,False,False,False,False,326,Southwark,0,0,inactive
19,13010,,W4 5EU,6,South Acton Allotments,51.499287,-0.270997,0,False,True,False,False,False,False,False,False,False,308,Ealing,0,0,inactive
20,6334,,W3 8TL,6,South Acton Allotment plot,51.500969,-0.270700,0,False,True,False,False,False,False,False,False,False,308,Ealing,0,0,active
21,13251,,W3 8SN,6,"Jerome Allotments, Acton",51.502655,-0.275885,0,False,True,False,False,False,False,False,False,False,308,Ealing,0,0,active
22,12960,,UB69DR,6,Windmill Lane Allotments,51.524158,-0.355524,1,False,True,False,False,False,False,False,False,False,308,Ealing,0,0,volunteers wanted
23,12531,,N1 6DB,6,Grown in Hoxton,51.527805,-0.084065,0,False,True,False,False,False,False,False,False,False,310,Hackney,0,0,active
24,13243,,E20 2AE,6,Event on 28 April: Food growing cultures in an...,51.536240,-0.013941,0,False,True,False,False,False,False,False,False,False,310,Hackney,0,1,active
25,6448,,N1 5TL,6,De Beauvoir Estate Garden Allotments,51.537643,-0.084318,0,False,True,False,False,False,False,False,False,False,310,Hackney,0,0,active
26,13376,,N1 8RU,6,"Green Man St Garden, Peabody Estate",51.539055,-0.097566,0,False,True,False,False,False,False,False,False,False,317,Islington,0,0,active
27,12880,,UB5 4RE,6,Oldfield Allotment,51.547401,-0.354710,0,False,True,False,False,False,False,False,False,False,308,Ealing,0,0,inactive
28,12872,,E9 6SR,6,Homerton Hospital Food Gardens,51.551437,-0.046313,1,False,True,False,False,False,False,False,False,False,310,Hackney,0,0,inactive
29,13357,,N1 4RF,6,The Garden Classroom,51.551407,-0.085246,0,False,True,False,False,False,False,False,False,False,317,Islington,0,0,active
30,12502,,E10 5BS,6,Soul Sow MO,51.560539,-0.017661,1,False,True,True,True,True,True,True,True,True,329,Waltham Forest,7,0,inactive
31,13382,,N52ls,6,Mountgrove Road in Bloom,51.560978,-0.094947,0,False,True,False,False,False,False,False,False,False,310,Hackney,0,0,active
32,12972,,E10 7LU,6,Plot 44 Seymour Road Allotments,51.566959,-0.026756,0,False,True,False,False,False,False,False,False,False,329,Waltham Forest,0,0,inactive
33,13434,,E10 7LU,6,Mandala Land,51.567135,-0.027287,1,False,True,True,True,False,False,False,False,False,329,Waltham Forest,2,0,volunteers wanted
34,13241,,N6 4DT,6,Highgate Allotments,51.578182,-0.155114,0,False,True,False,False,False,False,False,False,False,312,Haringey,0,0,active
35,12560,,N87AN,6,Campsbourne Food Garden Project,51.590881,-0.119028,0,False,True,False,False,False,False,False,False,False,312,Haringey,0,0,inactive
36,12450,,E17 6EN,6,Grow Together E17,51.592541,-0.030887,1,False,True,False,False,False,False,False,False,True,329,Waltham Forest,1,0,inactive
37,13378,,N10 1NU,6,Creighton Avenue Allotment,51.595860,-0.148782,0,False,True,False,False,False,False,False,False,False,312,Haringey,0,0,active
38,13430,,E17 5pr,6,Natural Gardeners,51.599651,-0.040115,1,False,True,True,True,True,True,False,True,True,329,Waltham Forest,6,0,volunteers wanted
39,228,,IG6 2XL,6,Forest Farm Peace Garden,51.600254,0.091605,1,True,True,True,False,True,False,True,False,False,324,Redbridge,3,2,volunteers wanted
40,13377,,N10 2EY,6,Hollickwood Community Garden,51.607815,-0.143033,0,False,True,False,False,False,False,False,False,False,256,Enfield,0,0,active
41,12956,,NW7 1BY,6,Sanders Lane Allotments,51.614002,-0.205873,0,False,True,False,False,False,False,False,False,False,302,Barnet,0,0,inactive
42,12683,,N12 7DX,6,Community Plot @ Whetstone,51.624378,-0.184180,1,False,True,True,True,True,True,True,False,False,302,Barnet,5,1,volunteers wanted
43,12364,,E4 8BS,6,Community Apothecary Mulberry Close Garden,51.626598,-0.015764,1,False,True,False,False,False,True,True,False,False,329,Waltham Forest,2,0,volunteers wanted
44,12171,,EN5 5NY,6,Plot 38a - Clifford Road Allotments,51.655872,-0.181925,0,False,True,False,False,False,False,False,False,False,302,Barnet,0,0,inactive
45,6155,,EN5 5PD,6,Plot 13,51.656803,-0.180088,0,False,True,False,False,False,False,False,False,False,302,Barnet,0,0,active

Space type 6 seems to be allotments

In [97]:
type_5 = df[df['space_type'].str.strip() == '5'].reset_index(drop=True)
type_5.head(50)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,12048,,SE6 1XT,5,Our Garden,51.443592,-0.003108,1,False,False,True,True,True,True,True,True,True,321,Lewisham,7,0,volunteers wanted
1,13091,,sw24py,5,Beaumont Court,51.445244,-0.125664,0,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,inactive
2,6003,,SE6 4UN,5,Jongar,51.445503,-0.035578,0,False,False,False,False,False,False,False,False,False,321,Lewisham,0,0,active
3,11709,,SE220QY,5,Rejuvination Gardens,51.445541,-0.067511,1,False,False,False,False,False,False,False,False,False,326,Southwark,0,1,volunteers wanted
4,13443,,SE136NS,5,21 Romborough Way,51.455139,-0.012667,1,False,False,False,True,False,True,True,True,True,321,Lewisham,5,0,volunteers wanted
5,13051,,SE24 9PJ,5,CasinoCrop,51.457226,-0.093148,1,False,False,True,True,True,True,True,True,True,326,Southwark,7,0,volunteers wanted
6,12819,,SW2 5UL,5,Balcony Garden,51.459904,-0.126764,1,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,inactive
7,13442,,se137aw,5,86 Algernon Road,51.461174,-0.018752,1,False,False,True,True,True,True,True,True,True,321,Lewisham,7,0,volunteers wanted
8,13045,,SE5 8BB,5,Ronald McDonald House Charities,51.468899,-0.088340,1,False,False,True,True,True,True,True,True,True,326,Southwark,7,1,volunteers wanted
9,11943,,SE5 9RA,5,Myatt&#39;s Fields Park home growing collective,51.472591,-0.105319,1,False,False,False,False,False,False,False,False,False,320,Lambeth,0,1,inactive
10,6790,,SE18 7BB,5,CosGrow,51.482693,0.070059,0,False,False,False,False,False,False,False,False,False,309,Greenwich,0,0,active
11,12847,,SW8 2JA,5,Balcony garden,51.485424,-0.126917,0,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,active
12,12597,,TW8 8BS,5,Plot Nine,51.485435,-0.313476,0,False,False,False,False,False,False,False,False,False,316,Hounslow,0,0,active
13,5380,,TW8 0PL,5,Hen Corner,51.485645,-0.305611,0,False,False,True,True,True,True,False,False,False,316,Hounslow,4,1,active
14,13022,,Sw7 5Pr,5,Ferney,51.498398,-0.181559,1,False,False,False,False,False,False,False,False,False,318,Kensington and Chelsea,0,0,inactive
15,5715,,E6 3SQ,5,My little bit of Newham,51.520897,0.046696,0,False,False,False,False,False,False,False,False,False,323,Newham,0,1,active
16,12840,,WC1X 9HA,5,Jedi&#39;s garden,51.530167,-0.113055,0,False,False,False,False,False,False,False,False,False,317,Islington,0,0,inactive
17,12143,,NW25JN,5,Private garden,51.546417,-0.226499,0,False,False,False,False,False,False,False,False,False,304,Brent,0,0,active
18,5986,,E8 1LA,5,Homegrown in Hackney,51.548435,-0.062059,0,False,False,False,False,False,False,False,False,False,310,Hackney,0,0,inactive
19,13439,,NW3 2SY,5,Seagrave Farm,51.556091,-0.164490,0,False,False,False,False,False,False,False,False,False,306,Camden,0,0,active
20,13096,,N5 1BN,5,Gem at Highbury,51.556915,-0.100562,1,False,False,True,False,True,False,True,False,False,300,City of London,3,0,volunteers wanted
21,12941,,HA9 7QX,5,Fox Garden,51.559673,-0.292821,0,False,False,False,False,False,False,False,False,False,304,Brent,0,0,inactive
22,6470,,N4 3HD,5,My garden,51.567913,-0.108314,0,False,False,False,False,False,False,False,False,False,312,Haringey,0,0,active
23,13139,,N19 3QH,5,26B Lambton Roof Terrace,51.569412,-0.122292,0,False,False,False,False,False,False,False,False,False,312,Haringey,0,0,active
24,5591,,E17 8HD,5,70 Hibbert Road,51.570766,-0.028222,0,False,False,False,False,False,False,False,False,False,329,Waltham Forest,0,0,inactive
25,6749,,N4 4BU,5,Parkland Patio Garden,51.570721,-0.107658,0,False,False,False,False,False,False,False,False,False,312,Haringey,0,0,inactive
26,13336,,N3 3ND,5,Turtle Box,51.594757,-0.197352,1,False,False,True,True,True,True,True,True,True,302,Barnet,7,0,volunteers wanted
27,13353,,E17 5BH,5,Time To Grow!,51.598408,-0.016891,1,False,False,False,False,False,False,False,False,False,329,Waltham Forest,0,0,volunteers wanted
28,13145,,IG8 9RS,5,Garden@35,51.612911,0.014827,0,False,False,False,False,False,False,False,False,False,329,Waltham Forest,0,0,active
29,12838,,N12 9DA,5,Home garden,51.615658,-0.174308,0,False,False,False,False,False,False,False,False,False,302,Barnet,0,0,inactive
30,6177,,N14 6LR,5,Backgarden,51.625465,-0.118447,0,False,False,False,False,False,False,False,False,False,256,Enfield,0,0,active

In [98]:
type_8 = df[df['space_type'].str.strip() == '8'].reset_index(drop=True)
type_8.head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,True,False,True,False,True,True,False,True,False,NaN,NaN,4,1,volunteers wanted
1,5974,,SW19 2RR,8,Deen City Farm,51.408070,-0.185497,1,False,False,True,True,True,True,True,False,False,322,Merton,5,0,inactive
2,12082,,SE24 9DB,8,TheFarmLondon,51.450020,-0.100316,0,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,active
3,5569,,SW9 7EL,8,Loughborough Farm,51.465889,-0.103149,1,False,False,False,True,False,False,False,True,False,320,Lambeth,2,2,volunteers wanted
4,13422,,SE5 9HY,8,Adi&#39;s Urban Mushroom Farm at The Remakery ...,51.470959,-0.102968,0,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,active
5,6191,,SE16 5ET,8,Surrey Docks Farm,51.499817,-0.033202,0,True,False,True,False,False,False,False,False,True,326,Southwark,2,25,active
6,13124,,EC4M 7BF,8,Barings,51.515713,-0.102406,0,False,False,False,False,False,False,False,False,False,300,City of London,0,0,active
7,11792,,E32AT,8,Food Forest - GET OUT permaculture garden,51.527653,-0.029531,1,False,False,False,False,False,True,False,True,False,328,Tower Hamlets,2,0,inactive
8,12719,,NW1 9SD,8,Foodscape,51.543179,-0.135197,1,False,False,False,False,False,False,False,False,False,306,Camden,0,0,volunteers wanted
9,11849,,E5 8HD,8,Clapton Square,51.552048,-0.055548,0,False,False,False,False,False,False,False,False,False,310,Hackney,0,0,inactive
10,11851,,E9 5PF,8,The Tree Nursery,51.552486,-0.024145,0,False,False,False,False,False,False,False,False,False,310,Hackney,0,0,inactive
11,4,,N16 7UE,8,St Pauls Church,51.554417,-0.079355,1,False,False,False,False,False,False,False,False,False,310,Hackney,0,1,inactive
12,6782,,N16 9HJ,8,Growing Commnunities Patchwork Farm Clissold site,51.560337,-0.087778,1,False,False,False,False,False,False,False,False,False,310,Hackney,0,1,volunteers wanted
13,11852,,N16 7ED,8,St Mike&#39;s,51.562737,-0.066494,0,False,False,False,False,False,False,False,False,False,310,Hackney,0,0,inactive
14,13278,,E5 9EF,8,Growing Communities Springfield market garden,51.569786,-0.059551,0,True,False,True,False,False,False,False,False,False,310,Hackney,1,1,active
15,12873,,E17 8AG,8,The Fungi Club,51.578831,-0.036016,1,False,False,False,False,False,False,False,False,False,329,Waltham Forest,0,0,inactive
16,13150,,N22 5JD,8,Wolves Lane Centre,51.604904,-0.103991,0,False,False,False,False,False,False,False,False,False,312,Haringey,0,1,active
17,12769,,N22 5JD,8,Wolves Lane Centre,51.608105,-0.102907,1,False,False,False,False,False,False,False,False,False,312,Haringey,0,2,volunteers wanted
18,12545,,E4 7UH,8,Organiclea,51.640724,-0.002891,1,False,False,False,False,True,False,True,False,False,329,Waltham Forest,2,1,volunteers wanted

In [99]:
type_2 = df[df['space_type'].str.strip() == '2'].reset_index(drop=True)
type_2.head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,5980,,CR4 3LB,2,Tamworth Farm Allotments,51.414364,-0.162648,0,False,False,False,False,False,False,False,False,False,322,Merton,0,0,active
1,6433,,SW2 3EE,2,Hillside Gardens Park Allotment,51.437408,-0.116221,0,False,False,False,False,False,False,False,False,False,320,Lambeth,0,0,inactive
2,6159,,w73rt,2,High Lane Allotments,51.521214,-0.348939,0,False,False,False,False,False,False,False,False,False,308,Ealing,0,0,active

In [100]:
type_3 = df[df['space_type'].str.strip() == '3'].reset_index(drop=True)
type_3.head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,6596,,SE8 3QH,3,John Evelyn Community Garden,51.490257,-0.035227,1,False,False,False,False,False,False,False,False,True,321,Lewisham,1,1,volunteers wanted
1,5922,,nw9 6lh,3,Sowing Seed Project,51.598068,-0.183304,1,False,False,True,True,True,True,True,False,False,302,Barnet,5,0,volunteers wanted

In [101]:
type_4 = df[df['space_type'].str.strip() == '4'].reset_index(drop=True)
type_4.head(20)

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status
0,6424,,EC1V 8AJ,4,St Luke's Food Growing Space,51.526688,-0.09574,1,False,False,False,True,False,True,False,False,False,317,Islington,2,0,volunteers wanted

In [102]:
df['project_decs'].value_counts()

project_decs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  377
5 raised beda and a pond.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Sutton Community Farm is a community-owned farm. We started in 2010 in response to a community need with the purpose to increase access to fresh, healthy, sustainable food and provide a shared space for people to cultivate skills, get exercise and make new friends. Our farm sits on a beautiful 7.1 acre smallholding with views towards the skyline of central London.&#13;&#10;We sell the vegetables we grow via our VegBox scheme which you can order online at suttoncommunityfarm.org.uk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
We have a regular food growing and volunteering session Fridays and we all enjoy a freshly prepared seasonal veggie lunch. We want to attract some new volunteers via the BIG DIG so please join us on Friday 26th or most other Fridays.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Applegarth Academy has a small but well equipped allotment area, located in a previously unused area in the heart of the school. We are proud to be able to grow our own vegetables which the children actively participate in and learn from, as well as understand healthy eating and sustainable living.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
We have a community allotment off Colston Avenue, Carshalton and a Walled Garden at EcoLocal offices, Honeywood Walk, Carshalton. We are looking for volunteers to help with either of these local food growing projects. Lear how to produce your own fresh, organic fruit and veggies and take home a share of the produce!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Our garden is made up of 6  garden&#39;rooms&#39;with a potager (kitchen garden),Flower Fairies garden,two herb gardens (medicinal &amp; culinary), Peace Garden and the cultural heritage garden.We grow fruit and vegetables, herbs and fruit trees alongside ornamental planting. We welcome young and older from babies to 100 and no gardening experience is required. We have people who volunteer regularly or those who drop in when they can.  We grow to meet, and meet to grow. Please come along and say hello!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
MHA The Wilderness is a 5 acre heritage woodland and wild garden originally created by Rev. William Wilks in 1904.  Having recently undergone a period of conservation, it is now a community garden focusing on wellbeing activities and volunteering opportunities to the local population and residents in next door MHA Hall Grange. In the last two years a small no-dig edible garden has been built, and worked on by various groups that benefit from using the garden.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Our aim is to create a community food growing space, transform a redundant flower bed into a sensory garden and save an existing rose garden. The community allotment will include accessible footpaths for the mobility impaired, as well as a host of green infrastructure features and pollinator-friendly planting to improve biodiversity.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Expanding on a food growing space to create new growing plots for the benefit of the community.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
&#13;&#10;<p>This project&nbsp;encourages community members, both&nbsp;young and old, to work together to restore a plot and to help keep the bee population fed.&nbsp;It is organised by committee members, with&nbsp;help from other members and their families. During October&nbsp;there is a&nbsp;volunteers day when&nbsp; members help on different projects.</p>&#13;&#10;<p>Members are cultivating a plot next to the space where the bee hives are kept, which is currently vacant and formerly overgrown&nbsp;&nbsp;They are building raised&nbsp;beds, as well as planting fruit trees, lavender, rosemary, sage, thyme and other&nbsp;perennial, nectar producing plants,&nbsp; This&nbsp;will help feed the bees throughout the year, ensuring they&nbsp;have sufficient nectar to produce honey, and&nbsp;enough food stored in thier hives to see them through the winter. </p>&#13;&#10;<p>There are future plans&nbsp;to create an area for small wildlife such as frogs, butterflies and ladybirds, all of which help the allotment holders keep pests at bay. It is&nbsp;also planned that next year there will be&nbsp;an open day at the allotment site&nbsp;when members of the community&nbsp;can visit and see what&nbsp;is being grown, as well as&nbsp;learn about bees and beekeeping.&nbsp; </p>      1
A community orchard containing around 40 different fruit trees and bushes, with herbs and flowers in small raised beds. The site is on a narrow strip of land, shielded from the footpath running alongside by a mixed native hedge. There is a wild area with a pond at one end.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Name: count, dtype: int64

Project descrition only available for first 10, 
The reason you only see a handful of non‐blank project_decs in the XML dump is that the map endpoint is deliberately kept “light” – it only emits a short blurb (or whatever legacy snippet exists) for a handful of spaces. The full write-ups you see on the site are loaded on demand when you click through to a space’s Detail page (via that fancy iframe /processors/mapEntry.php?space_id=… call), not in the bulk XML feed.

In [103]:
import requests
from bs4 import BeautifulSoup

def fetch_space_details(space_id):
    """
    Given a space_id, load the mapEntry iframe and scrape out:
      - full_description
      - run_by
      - campaign_name, campaign_url
      - website_url
      - social_links: list of {platform, url}
    """
    url = f"https://www.capitalgrowth.org/processors/mapEntry.php?space_id={space_id}&area_url=london"
    resp = requests.get(url)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")
    
    # 1) Full description = first <p class="bot15"> (but *not* the one with "Run by")
    desc_p = soup.find_all("p", class_="bot15")
    full_desc = ""
    for p in desc_p:
        # skip the one that has <strong>Run by</strong>
        if p.find("strong", string=lambda s: s and "Run by" in s):
            continue
        full_desc = p.get_text(" ", strip=True)
        break


    # 3) Campaign panel (<p class="gpanel">)
    camp_p = soup.find("p", class_="gpanel")
    campaign_name = campaign_url = ""
    if camp_p:
        a = camp_p.find("a", href=True)
        if a:
            campaign_name = a.get_text(strip=True)

    # 4) Website button
    site_btn = soup.find("a", class_="btn btn-default", href=True)
    website_url = site_btn["href"] if site_btn else ""

       # 5) Social links in the Location panel
    social_links = []
    loc_block = soup.find("div", class_="col-sm-7 bot25 borderTop0")
    if loc_block:
        # look at each <p class="bot25"> under that div
        for p in loc_block.find_all("p", class_="bot25"):
            for a in p.find_all("a", href=True):
                href = a["href"]
                text = a.get_text(strip=True)
                # infer platform
                if "twitter.com" in href:
                    platform = "Twitter"
                elif "facebook.com" in href:
                    platform = "Facebook"
                else:
                    # fallback to link text or hostname
                    platform = text or href.split("//")[-1].split("/")[0]
                social_links.append({"platform": platform, "url": href})

    return {
        "space_id":      space_id,
        "full_desc":     full_desc,
        "campaign_name": campaign_name,
        "website_url":   website_url,
        "social_links":  social_links
    }

In [104]:
from tqdm import tqdm

# fetch into a list of dicts
all_details = []
for sid in tqdm(df["space_id"].unique()):
    try:
        all_details.append(fetch_space_details(sid))
    except Exception as e:
        print("failed", sid, e)

# build a small DataFrame and join
details_df = pd.DataFrame(all_details).set_index("space_id")
details_df.head(50)

100%|██████████| 388/388 [00:28<00:00, 13.59it/s]

,full_desc,campaign_name,website_url,social_links
space_id,,,,
6200,5 raised beda and a pond.,,http://oasiscoulsdon.org,[]
309,Sutton Community Farm is a community-owned far...,,http://www.suttoncommunityfarm.org.uk,[]
11522,We have a regular food growing and volunteerin...,,http://www.goodfoodmatters.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13116,Applegarth Academy has a small but well equipp...,,,[]
13156,We have a community allotment off Colston Aven...,Growing For Change,http://www.ecolocal.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
5828,Our garden is made up of 6 garden'rooms'with ...,,,[]
13424,MHA The Wilderness is a 5 acre heritage woodla...,,https://mha.org.uk/care-support/types-care-sup...,"[{'platform': 'mhathewilderness', 'url': 'http..."
12469,Our aim is to create a community food growing ...,,,[]
3,Expanding on a food growing space to create ne...,,http://www.mayproject.org,[]
2792,"This project encourages community members, bot...",,,[]
12069,A community orchard containing around 40 diffe...,Growing For Change,https://www.sustainablemerton.org/growingspaces,"[{'platform': 'Twitter', 'url': 'https://twitt..."
23,12 years ago over 100 volunteers helped to con...,,http://www.sustainablemerton.org,"[{'platform': 'Twitter', 'url': 'https://twitt..."
5974,Our space is a tranquil community garden withi...,,http://www.deencityfarm.co.uk,[]
13077,A 1-acre plot on the school grounds of Woodman...,,,"[{'platform': 'woodmansterneschoolfarm', 'url'..."
5980,Three linked allotment spaces known as The Hor...,,,[]
6405,Wimbledon Guild is a community charity in Mert...,Growing For Change,http://www.wimbledonguild.co.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13147,Plot 1 is an individual freehold allotment in ...,,,[]
13224,Rockmount's garden was started with an investm...,Growing For Change,,[]
13104,Our volunteer gardeners work with professional...,,https://invisiblepalace.org.uk/what-we-do,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13161,"Discover Holderness Way Community Garden, wher...",,https://www.goodtogrowuk.org/login/?pid=&view=2,"[{'platform': 'holdernesswaygarden', 'url': 'h..."
6359,A former gardeners' yard on the edge of Canbur...,Growing For Change,https://e-voice.org.uk/ttkingston/ttk-groups-a...,"[{'platform': 'Facebook', 'url': 'https://www...."
13244,"Raised beds for food and companion flowers, fr...",Growing For Change,,[]
482,Nestled in the corner of a suburban allotment ...,,,[]
13072,"Community Allotment space, boardering council ...",,http://Www.growlewisham.com,"[{'platform': 'growlewisham', 'url': 'https://..."
13181,We have a mini beast friendly border in the fr...,Growing For Change,http://www.benedicthouseprepschool.co.uk,"[{'platform': 'Facebook', 'url': 'https://www...."
12001,A Community Garden run by Grow Lewisham.\r\n\r...,,https://www.growlewisham.com/,"[{'platform': 'growlewisham', 'url': 'https://..."
12036,We are a community-led project aiming to grow ...,,https://www.railsidegarden.org.uk/,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13362,"In 2023, the Bowls club offered an overgrown a...",,,[]
13230,We have just received the allotment plot that ...,Growing For Change,http://www.ucy.org.uk,"[{'platform': 'unitedchildrenandyouth', 'url':..."
13461,"At Kingswood Arts, our mission is to foster cr...",,http://kingswoodarts.com,[]
487,The project will transform one acre of disused...,,http://www.sydenhamgarden.org.uk/news-events/e...,[]
6442,Tritton Vale Pocket Garden was created in 2016...,,http://www.facebook.com/trittonroad/,"[{'platform': 'trittonvalepocketgarden', 'url'..."
12743,We are a new Afro-diaspora led community garde...,Growing For Change,Eventbrite: https://www.eventbrite.co.uk/o/coc...,"[{'platform': 'cococollective_org', 'url': 'ht..."
12902,The Friends of Forster Memorial Park sensory g...,,https://forsterparkfriends.org/,"[{'platform': 'Forstermemorialpark', 'url': 'h..."
12897,Countisbury Veg Community Allotment is a veg g...,,,[]
5903,The Wild Cat Wilderness is a community green s...,,http://www.wildcatwilderness.org,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13448,A community growing area within Hillside Garde...,,https://www.hillsidegardenspark.co.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
6433,Hillside Gardens Park Allotment space is a gar...,,http://www.hillsidegardenspark.co.uk/,[]
13182,"The park overall is Hillside Gardens, there is...",,https://hillsidegardenspark.co.uk/,"[{'platform': 'Twitter', 'url': 'https://twitt..."
6214,garden on a portion of flat roof on a new buil...,,http://www.the-elmgreen-school.org.uk/,[]
13426,"Share Garden is a site of Share Community, a c...",,https://www.sharecommunity.org.uk/what-we-do/s...,[]
11704,We have a botanic garden in which we grow some...,,http://www.slbi.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13132,Roots4life is set on a beautiful 8.6 acre site...,,http://Www.Roots4life.org,"[{'platform': '@roots_forlife', 'url': 'https:..."
13418,Lewisham Allotment site.,,,[]
12983,"Welcome to our new 2nd site, a youth led commu...",,,"[{'platform': 'cococollective_org', 'url': 'ht..."
13118,A ten-rod plot within a council-run allotment ...,,,[]
12048,We grow food for our intentional community. We...,,,"[{'platform': 'Twitter', 'url': 'https://twitt..."
13108,Eight raised beds for use of Melford Court res...,,,[]
13091,"Communal garden, private to people living on t...",,,[]
6003,each year we grown our tomatoes (six plants) B...,Growing For Change,,[]

In [105]:
len(details_df )
#checking size matches

388

In [106]:
# adding details_df to main df
df = df.set_index("space_id").join(details_df, how="left").reset_index()

In [107]:
df

,space_id,project_decs,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_id,poly_name,vol_days_count,event_days_count,status,full_desc,campaign_name,website_url,social_links
0,6200,5 raised beda and a pond.,CR5 1QR,7,Science Garden,51.299297,-0.111720,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active,5 raised beda and a pond.,,http://oasiscoulsdon.org,[]
1,309,Sutton Community Farm is a community-owned far...,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,True,False,True,False,True,True,False,True,False,NaN,NaN,4,1,volunteers wanted,Sutton Community Farm is a community-owned far...,,http://www.suttoncommunityfarm.org.uk,[]
2,11522,We have a regular food growing and volunteerin...,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,1,False,True,False,False,False,False,True,False,False,NaN,NaN,1,1,inactive,We have a regular food growing and volunteerin...,,http://www.goodfoodmatters.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
3,13116,Applegarth Academy has a small but well equipp...,CR09DL,7,Applegarth Academy,51.354790,-0.026161,0,False,False,False,False,False,False,False,False,False,NaN,NaN,0,0,active,Applegarth Academy has a small but well equipp...,,,[]
4,13156,We have a community allotment off Colston Aven...,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,False,True,False,False,False,False,False,False,False,NaN,NaN,0,0,volunteers wanted,We have a community allotment off Colston Aven...,Growing For Change,http://www.ecolocal.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,13454,,EN5 4BD,1,Robin Community Garden,51.652317,-0.202375,1,False,True,False,False,False,False,False,False,False,302,Barnet,0,0,volunteers wanted,The Robin Community Garden is a small garden w...,,,[]
384,12171,,EN5 5NY,6,Plot 38a - Clifford Road Allotments,51.655872,-0.181925,0,False,True,False,False,False,False,False,False,False,302,Barnet,0,0,inactive,We have a half-sized plot on the Clifford Road...,,http://www.crallotments.org.uk/index.html,[]
385,6155,,EN5 5PD,6,Plot 13,51.656803,-0.180088,0,False,True,False,False,False,False,False,False,False,302,Barnet,0,0,active,"227 square metres (9 poles) 3 raised beds, 2 b...",,,[]
386,13320,,EN13UL,7,St Andrew&#39;s CE Primary School,51.657230,-0.078583,0,False,False,False,False,False,False,False,False,False,256,Enfield,0,0,active,We are just beginning our growing journey. We...,,,[]
387,6710,,EN3 6HG,7,Prince of Wales Primary School Organic Gardens,51.668629,-0.022429,1,False,False,False,False,False,False,False,False,False,256,Enfield,0,0,inactive,We have a number of raised beds around the sit...,,http://www.princeofwales.enfield.sch.uk/,[]

In [108]:
df = df.drop(columns=['project_decs'], errors='ignore')

Note that vol_days_count may show up as 0 for many places that don't have the volunteering days showing on the website, so not very accurate.

In [109]:
df['campaign_name'].value_counts()

campaign_name
                      294
Growing For Change     65
Cordwainers Grow       29
Name: count, dtype: int64

In [110]:
df['vol_days_count'].value_counts()

vol_days_count
0    239
1     50
2     37
7     28
3     20
5      7
4      4
6      3
Name: count, dtype: int64

In [111]:
df = df.drop(columns=['poly_id'])
df.head()

,space_id,space_postcode,space_type,space_name,lat,lng,vol_required,in_next_event,allotmentsMarker,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,poly_name,vol_days_count,event_days_count,status,full_desc,campaign_name,website_url,social_links
0,6200,CR5 1QR,7,Science Garden,51.299297,-0.111720,0,False,False,False,False,False,False,False,False,False,NaN,0,0,active,5 raised beda and a pond.,,http://oasiscoulsdon.org,[]
1,309,SM6 0SH,8,Sutton Community Farm,51.341320,-0.155031,1,True,False,True,False,True,True,False,True,False,NaN,4,1,volunteers wanted,Sutton Community Farm is a community-owned far...,,http://www.suttoncommunityfarm.org.uk,[]
2,11522,CR0 0PN,1,GOOD FOOD MATTERS,51.352913,-0.008018,1,False,True,False,False,False,False,True,False,False,NaN,1,1,inactive,We have a regular food growing and volunteerin...,,http://www.goodfoodmatters.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."
3,13116,CR09DL,7,Applegarth Academy,51.354790,-0.026161,0,False,False,False,False,False,False,False,False,False,NaN,0,0,active,Applegarth Academy has a small but well equipp...,,,[]
4,13156,SM5 3BY,1,EcoLocal,51.365517,-0.164828,1,False,True,False,False,False,False,False,False,False,NaN,0,0,volunteers wanted,We have a community allotment off Colston Aven...,Growing For Change,http://www.ecolocal.org.uk,"[{'platform': 'Twitter', 'url': 'https://twitt..."

In [112]:
df['event_days_count'].value_counts()

event_days_count
0     261
1     107
2      12
3       4
4       2
25      1
5       1
Name: count, dtype: int64

In [113]:
# converting space_type to integer for correlation capacity + making new status_code column

df['space_type'] = df['space_type'].astype(int)

status_map = {'active':0,'inactive':1,'volunteers wanted':2}
df['status_code'] = df['status'].map(status_map)

In [114]:

from sklearn.feature_extraction.text import TfidfVectorizer

# building one “document” per space_type by concatenating name+description
grouped = (
    df
    .fillna({'full_desc': ''})
    .groupby('space_type')[['space_name','full_desc']]
    .apply(lambda g: " ".join((g['space_name'] + " " + g['full_desc']).tolist()))
    # result is a Series indexed by space_type
)

# running tf-idf on this Series
vectorizer = TfidfVectorizer(ngram_range=(1,3),
    max_df=0.99,      # ignore very common words
    min_df=1,        # ignore super-rare words
    stop_words='english'
)
tfidf_matrix = vectorizer.fit_transform(grouped.values)
terms = vectorizer.get_feature_names_out()

# tf-idf dataframe
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    index=grouped.index,
    columns=terms
)

# showing top unigrams, bigrams, and trigrams for each space_type
top_n = 10
for space_type, row in tfidf_df.iterrows():
    top_terms = row.nlargest(top_n).index.tolist()
    print(f"Type {space_type}: {', '.join(top_terms)}")

Type 1: growing, community garden, local, residents, park, grow, gardens, open, energy, project
Type 2: park, gardens park allotment, park allotment, allotment, gardens park, hillside, hillside gardens, hillside gardens park, allotments, plots
Type 3: service, service users, users, place, used, 10 service, 10 service users, 30 square, 30 square meters, activities place
Type 4: luke, st luke, gardening sessions, gardening, sessions, st, 076, 07983, 07983 508, 07983 508 076
Type 5: growing, fruit, home, herbs, grow, pots, private, containers, private garden, beds
Type 6: allotment, plot, allotments, growing, site, estate, vegetables, allotment site, beds, grow
Type 7: school, children, primary school, growing, primary, beds, school garden, project, raised, area
Type 8: growing, farm, wolves, wolves lane, fungi, lane centre, loughborough, wolves lane centre, grow, centre

In [115]:
df['space_type'].value_counts()

space_type
1    240
7     46
6     46
5     31
8     19
2      3
3      2
4      1
Name: count, dtype: int64

In [116]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import chi2, SelectKBest

# 1) build document‐term matrix for each space 
cv = CountVectorizer(stop_words='english', ngram_range=(1,2))
X = cv.fit_transform(df['full_desc'].fillna(''))
y = df['space_type']

# 2) for each type vs. rest, pick top k features 
top_features = {}
for t in df['space_type'].unique():
    chi2_scores, p_vals = chi2(X, (y == t).astype(int))
    idxs = np.argsort(chi2_scores)[-10:]
    top_features[t] = [cv.get_feature_names_out()[i] for i in idxs]

In [117]:


# turn into a DataFrame: rows are types, columns are the top k features
df_feats = pd.DataFrame.from_dict(
    top_features, 
    orient='index', 
    columns=[f"top{i+1}" for i in range(len(next(iter(top_features.values()))))]
)
df_pretty = df_feats.T
df_pretty.index.name = "feature_rank"
print(df_pretty)

                           7                    8                 1  \
feature_rank
top1          primary school  workers cooperative            energy
top2           school garden          cooperative         residents
top3                     let             mushroom          children
top4                 lessons               wolves            garden
top5                  pupils          wolves lane             local
top6                 grounds                 lane              plot
top7                 science                fungi  community garden
top8                students                 zone              open
top9                children         loughborough            school
top10                 school                 farm         community

                              2               6               5  \
feature_rank
top1              avenue strong      allotments        property
top2           linked allotment  allotment plot    garden fruit
top3          community sharing          barnet          moment
top4                  farm rose           plots            good
top5                         41            tate            soil
top6                   site set       socialise      large pots
top7               site improve  residents grow  private garden
top8          community managed  allotment site         private
top9                food hedges            plot      containers
top10          allotment spaces       allotment            pots

                             3                   4
feature_rank
top1            nature growing      thursdays 30pm
top2              used service          alok ashah
top3            barnet refugee  tuesdays thursdays
top4                10 service       emailing alok
top5          meters allotment       open tuesdays
top6              users barnet         edible yard
top7              learn nature     sessions spaces
top8                     users       sessions open
top9                   service    advance emailing
top10            service users            yard run

In [118]:
type1 = df.loc[df['space_type'] == 1, ['space_name', 'full_desc']]
type1.head(50)

,space_name,full_desc
2,GOOD FOOD MATTERS,We have a regular food growing and volunteerin...
4,EcoLocal,We have a community allotment off Colston Aven...
5,Park Hill Park Community Garden,Our garden is made up of 6 garden'rooms'with ...
6,MHA The Wilderness,MHA The Wilderness is a 5 acre heritage woodla...
7,Fishponds Community Garden,Our aim is to create a community food growing ...
8,May Project Food Growing project,Expanding on a food growing space to create ne...
9,Southlands Road Allotments,"This project encourages community members, bot..."
10,Mitcham Community Orchard and Gardens,A community orchard containing around 40 diffe...
11,Phipps Bridge Community Garden,12 years ago over 100 volunteers helped to con...
15,Wimbledon Guild Community Garden,Wimbledon Guild is a community charity in Mert...
18,Invisible Palace,Our volunteer gardeners work with professional...
19,Holderness Way Communal Garden,"Discover Holderness Way Community Garden, wher..."
20,Canbury Community Garden,A former gardeners' yard on the edge of Canbur...
21,Norwood Park community gardens,"Raised beds for food and companion flowers, fr..."
22,Parkfields Community Garden,Nestled in the corner of a suburban allotment ...
25,The Plot,A Community Garden run by Grow Lewisham.\r\n\r...
26,Railside Community Garden,We are a community-led project aiming to grow ...
27,Furzedown Project&#39;s Furzedown Farmers&#39;...,"In 2023, the Bowls club offered an overgrown a..."
29,Kingswood Arts Community Garden,"At Kingswood Arts, our mission is to foster cr..."
30,Sydenham Garden Food Growing Space,The project will transform one acre of disused...
31,Tritton Vale Pocket Garden,Tritton Vale Pocket Garden was created in 2016...
32,Ital Community Garden,We are a new Afro-diaspora led community garde...
33,Forster Memorial Park Sensory Garden,The Friends of Forster Memorial Park sensory g...
34,Countisbury Veg Community Allotment,Countisbury Veg Community Allotment is a veg g...
35,Wild Cat Wilderness,The Wild Cat Wilderness is a community green s...
36,Hillside Gardens Community Growing Area,A community growing area within Hillside Garde...
40,Share Garden,"Share Garden is a site of Share Community, a c..."
41,South London Botanical Institute,We have a botanic garden in which we grow some...
42,Roots4life,Roots4life is set on a beautiful 8.6 acre site...
44,"Ital Community Garden, Catford","Welcome to our new 2nd site, a youth led commu..."
51,Blythe Hill Fields Community Garden and Orchard,"Community Orchard with 12 trees, shrubs and fo..."
54,Agnes Riley Community Garden,A community garden located in Agnes Riley Gard...
55,Roupell Park Pocket Garden,"A social, play, grow and gathering space for t..."
58,The Paradise Cooperative,Paradise Co-operative is a registered charity ...
59,Lewisham Park Herbal Plot,We are located behind the flats at 56 Lewisham...
60,Windmill Gardens,Windmill Gardens is a small public park that i...
61,Brixton Flour,Windmill Gardens in Brixton Hill is a small pa...
64,Putney Community Gardens,We are a patchwork of wild and growing spaces ...
65,ETNA Community Centre Garden,We expanded our community kitchen in 2020 and ...
66,Clapham Common Bandstand Beds,Bandstand Beds (BBA) is a food growing project...
68,Effra Green Streets,Effra Green Streets is part of Lambeth Living ...
69,The Brixton Orchard,A colourful and welcoming community-based orch...
70,RU Outdoors / Growhampton,Roehampton University has developed a space on...
72,Denmark Hill Community Garden,Denmark Hill Community Garden is an open allot...
74,Frendsbury Gardens,We are a small community garden run by volunte...
75,Limes Walk TRA,Community garden for the tenants and residents...
76,St. Francis Food Forest,A community-led food forest and composting pro...
78,Brockley Energy Garden,Brockley is one of 34 gardens on the London Ov...
80,Bromar Garage Garden,Garage Garden is a food forest demo garden cre...
81,Battersea Arts Centre Community Garden,Battersea Arts Centre is an internationally re...

In [120]:
import nltk
nltk.data.path.append('/Users/student/Documents/CODE/myenv/nltk_data')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

In [121]:
import re
import html
import string

from nltk.tokenize import word_tokenize
from nltk.corpus   import stopwords
from nltk.stem     import WordNetLemmatizer

# Pre-compile your cleaner objects
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
punct_trans = str.maketrans(string.punctuation, ' ' * len(string.punctuation))

def clean_and_lemmatize(text: str) -> str:
    # 1) strip HTML and unescape entities
    text = re.sub(r'<[^>]+>', ' ', text)
    text = html.unescape(text)

    # 2) lowercase & remove punctuation
    text = text.lower().translate(punct_trans)

    # 3) remove stray numbers
    text = re.sub(r'\b[\d]+\b', ' ', text)

    # 4) tokenize, remove stopwords and non-alpha, then lemmatize
    tokens = word_tokenize(text)
    clean_tokens = []
    for tok in tokens:
        if tok.isalpha() and tok not in stop_words:
            lemma = lemmatizer.lemmatize(tok)
            clean_tokens.append(lemma)
    return " ".join(clean_tokens)

# Apply to your DataFrame
df['corpus'] = (df['space_name'].fillna('') + ' ' + df['full_desc'].fillna(''))
df['corpus'] = df['corpus'].apply(clean_and_lemmatize)

In [122]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

# 1) per-space TF-IDF with binary term presence
tfidf = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,3),
    binary=True,
    norm='l2'  # default
)
X = tfidf.fit_transform(df['corpus'].fillna(''))
terms = tfidf.get_feature_names_out()

# 2) make a DataFrame
tfidf_df = pd.DataFrame(X.toarray(), index=df.index, columns=terms)

# 3) average TF-IDF by space_type
avg_by_type = tfidf_df.join(df['space_type']).groupby('space_type').mean()

# 4) see top terms per type
for t, row in avg_by_type.iterrows():
    top10 = row.nlargest(10).index.tolist()
    print(f"Type {t}: {', '.join(top10)}")

Type 1: community, garden, community garden, growing, space, food, local, grow, garden community, open
Type 2: allotment space, allotment site set, brent river, brent river park, high, high lane, high lane allotment, lane allotment site, park plot, river park
Type 3: art creative, art creative activity, creative activity place, enjoy learn, enjoy learn nature, evelyn, evelyn community, evelyn community garden, food locally, food locally organic
Type 4: advance, advance emailing, advance emailing alok, alok, alok ashah, alok ashah slpt, ashah, ashah slpt, ashah slpt org, calling
Type 5: garden, private, fruit, private garden, herb, home, pot, ferney, ferney started, garden private
Type 6: allotment, plot, allotment plot, site, allotment site, allotment allotment, estate, community, vegetable, raised
Type 7: school, primary, primary school, garden, child, raised, school garden, bed, raised bed, science
Type 8: farm, growing, site, salad, food, space, run, enterprise, nursery, patchwork

Type 1 seems to be community gardens. Type 2 seems to be park allotments. Type 3 seems to be creative arts related. Type 4 from inspecting the single entry is church-run garden. Type 5 seems to be private gardens. Type 6 seems to be allotments, including community-owned allotment-style plots. Type 7 seems to be schools/ education related. Type 8 seems to be farms, including community-run.

In [123]:
# 1. Define your mapping (adjust the strings to taste)
type_name_map = {
    1: "General Community Gardens",
    2: "Park Allotments",
    3: "Creative Arts Gardens",
    4: "Church-run Gardens",
    5: "Private Gardens",
    6: "Allotment Plots",
    7: "School / Educational Gardens",
    8: "Farms"
}

# 2. If your space_type column is a string, convert to int first:
df['space_type'] = df['space_type'].astype(int)

# 3. Create the new descriptive column
df['space_type_name'] = df['space_type'].map(type_name_map)

# 4. Optional sanity-check
print(df[['space_type','space_type_name']].drop_duplicates().sort_values('space_type'))

     space_type               space_type_name
2             1     General Community Gardens
14            2               Park Allotments
143           3         Creative Arts Gardens
202           4            Church-run Gardens
46            5               Private Gardens
16            6               Allotment Plots
0             7  School / Educational Gardens
1             8                         Farms

In [124]:
df.to_csv('/Users/student/Documents/CODE/myenv/capstone data/capitalgrowth-london.csv', index=False)